force-app/main/default/objects/Quote/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en_US</fullName>
                <label>EN</label>
            </value>
            <value>
                <fullName>cs</fullName>
                <label>CS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RowDiscount__c.field-meta.xml
<CustomField>
    <fullName>RowDiscount__c</fullName>
    <label>Row Discount</label>
    <precision>15</precision>
    <scale>12</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RowTotalPrice__c.field-meta.xml
<CustomField>
    <fullName>RowTotalPrice__c</fullName>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SyncServiceSettings__c/SyncServiceSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SyncServiceSettings</label>
</CustomObject>

force-app/main/default/objects/SyncServiceSettings__c/fields/DisableSync__c.field-meta.xml
<CustomField>
    <fullName>DisableSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QuotePdfControllerTest.cls
@isTest 
private class QuotePdfControllerTest {

    @isTest
    private static void QuotePdfControllerTest() {
    SyncServiceSettings__c stt = new SyncServiceSettings__c();
        stt.Name = 'AccountToSAP';
        stt.DisableSync__c = true;
        insert stt;

        Opportunity opp = new Opportunity(StageName='Qualification', Name='Opp Test', CloseDate=Date.newInstance(2019, 8, 24)); 
        insert opp;
        Quote qt = new Quote(Name='Quote Test', OpportunityId=opp.Id, Language__c='cs');
        insert qt;
        
        Id pricebookId = Test.getStandardPricebookId();
        Product2 prod = new Product2(Name='Product', IsActive=true);
        insert prod;
        PricebookEntry pbe = [SELECT Id FROM PricebookEntry WHERE Product2Id=:prod.Id AND CurrencyIsoCode=:Cst.CURR_CZK AND IsActive=true LIMIT 1];
        
        QuoteLineItem qlis = new QuoteLineItem(QuoteId=qt.Id, PricebookEntryId=pbe.Id, Product2Id=prod.Id, Quantity=2, UnitPrice=100.00, UnitPrice__c=100.00, RowTotalPrice__c=200, RowDiscount__c=0);
        insert qlis;
        
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(qt);
        QuotePdfController ctrl = new QuotePdfController(stdCtrl);
    }
}