force-app/main/default/objects/TechnicianPricebookEntrySettings__c/TechnicianPricebookEntrySettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Technician Pricebook Entry Settings</label>
</CustomObject>

force-app/main/default/objects/TechnicianPricebookEntrySettings__c/fields/SessionId__c.field-meta.xml
<CustomField>
    <fullName>SessionId__c</fullName>
    <label>Session Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TechnicianPricebookEntrySchedulable.cls
public with sharing class TechnicianPricebookEntrySchedulable implements Schedulable{
    public final static String JOB_NAME_BASE = 'Technician Pricebook Entry Schedulable';
	public static String cron = '0 30 * ? * *';

	// Schedule Job
	public static void scheduleJob() {
		String jobName = JOB_NAME_BASE;
		if(Test.isRunningTest()){
			jobName += ' TEST';
		}
		System.debug('Scheduling ' + jobName);
		System.schedule(jobName, cron, new TechnicianPricebookEntrySchedulable());
	}

	// Execute
	public void execute(SchedulableContext sc) {
		worker();
	}

	// Global Cancel
	public static void cancel() {
		String jobName = JOB_NAME_BASE;
		if(Test.isRunningTest()){
			jobName += ' TEST';
		}
		CronTrigger[] cts = [SELECT Id, CronExpression, CronJobDetailId, CronJobDetail.Name, State FROM CronTrigger WHERE CronJobDetail.Name = :jobName];
		for (CronTrigger c : cts) {
			System.abortJob(c.ID);
			System.debug('Cron Job ' + c.CronJobDetail.Name + ' (' + c.ID + ') aborted.');
		}
	}


    public static void worker(){
        TechnicianPricebookEntrySettings__c tpbes = TechnicianPricebookEntrySettings__c.getValues('default');
        tpbes.SessionId__c = UserInfo.getSessionId();
        update tpbes;
    }
}