force-app/main/default/objects/Product2/fields/BusinessName__c.field-meta.xml
<CustomField>
    <fullName>BusinessName__c</fullName>
    <label>Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BusinessNameEN__c.field-meta.xml
<CustomField>
    <fullName>BusinessNameEN__c</fullName>
    <label>Business Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductDescriptionCZ__c.field-meta.xml
<CustomField>
    <fullName>ProductDescriptionCZ__c</fullName>
    <label>Product Description CZ</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductDescriptionEN__c.field-meta.xml
<CustomField>
    <fullName>ProductDescriptionEN__c</fullName>
    <label>Product Description EN</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Specification__c.field-meta.xml
<CustomField>
    <fullName>Specification__c</fullName>
    <label>Specification</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductSpecification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M-AKU_PENA</fullName>
            </value>
            <value>
                <fullName>M-BARVY</fullName>
            </value>
            <value>
                <fullName>M-DROBNY_SPMAT</fullName>
            </value>
            <value>
                <fullName>M-ELEKTRO</fullName>
            </value>
            <value>
                <fullName>M-FUKUMA</fullName>
            </value>
            <value>
                <fullName>M-KOV</fullName>
            </value>
            <value>
                <fullName>M-KOVANI</fullName>
            </value>
            <value>
                <fullName>M-LATKA</fullName>
            </value>
            <value>
                <fullName>M-MICROOFFICE</fullName>
            </value>
            <value>
                <fullName>M-OBALY</fullName>
            </value>
            <value>
                <fullName>M-OSTATNI</fullName>
            </value>
            <value>
                <fullName>M-PLOSNY_MAT</fullName>
            </value>
            <value>
                <fullName>M-SKLO</fullName>
            </value>
            <value>
                <fullName>P-POLOTOVAR</fullName>
            </value>
            <value>
                <fullName>S-SKLADOVE SLUZBY</fullName>
            </value>
            <value>
                <fullName>S-SLUZBY</fullName>
            </value>
            <value>
                <fullName>V-VYROBEK</fullName>
            </value>
            <value>
                <fullName>Z-ZBOZI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QLIDescription__c/QLIDescription__c.object-meta.xml
<CustomObject>
    <label>QLI Description</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QLI Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QLIDescription__c/fields/QuoteLineItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>QLI Descriptions</relationshipLabel>
    <relationshipName>QLIDescriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Quote/fields/IsApproved__c.field-meta.xml
<CustomField>
    <fullName>IsApproved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en_US</fullName>
                <label>EN</label>
            </value>
            <value>
                <fullName>cs</fullName>
                <label>CS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/NeedApprove__c.field-meta.xml
<CustomField>
    <fullName>NeedApprove__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need Approve</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QPdf_IsDisplayDiscount__c.field-meta.xml
<CustomField>
    <fullName>QPdf_IsDisplayDiscount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Discount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QPdf_IsDisplayDiscountUnitPrice__c.field-meta.xml
<CustomField>
    <fullName>QPdf_IsDisplayDiscountUnitPrice__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Display Unit Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QPdf_IsDisplayListPrice__c.field-meta.xml
<CustomField>
    <fullName>QPdf_IsDisplayListPrice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display List Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QPdf_IsDisplayProductSubtotal__c.field-meta.xml
<CustomField>
    <fullName>QPdf_IsDisplayProductSubtotal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Product Subtotal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QPdf_IsDisplayQuoteDiscount__c.field-meta.xml
<CustomField>
    <fullName>QPdf_IsDisplayQuoteDiscount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Quote Discount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QPdf_IsDisplayQuoteSubtotalPrice__c.field-meta.xml
<CustomField>
    <fullName>QPdf_IsDisplayQuoteSubtotalPrice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Quote Subtotal Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QPdf_IsDisplayQuoteTotalPrice__c.field-meta.xml
<CustomField>
    <fullName>QPdf_IsDisplayQuoteTotalPrice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Quote Total Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QuoteDiscount__c.field-meta.xml
<CustomField>
    <fullName>QuoteDiscount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quote Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QuoteNo__c.field-meta.xml
<CustomField>
    <fullName>QuoteNo__c</fullName>
    <description>&lt;ProjectNumber&gt;.&lt;OppNo&gt;.&lt;QuoteVersion&gt;</description>
    <inlineHelpText>&lt;ProjectNumber&gt;.&lt;OppNo&gt;.&lt;QuoteVersion&gt;</inlineHelpText>
    <label>Quote No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TechnicianId__c.field-meta.xml
<CustomField>
    <fullName>TechnicianId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TechnicianUserId__c.field-meta.xml
<CustomField>
    <fullName>TechnicianUserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IsShowInQuotePDF__c.field-meta.xml
<CustomField>
    <fullName>IsShowInQuotePDF__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Show in QuotePDF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IsTransport__c.field-meta.xml
<CustomField>
    <fullName>IsTransport__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if row is specific type of Transport.</description>
    <inlineHelpText>Determines if row is specific type of Transport.</inlineHelpText>
    <label>Transport</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProductFamily__c.field-meta.xml
<CustomField>
    <fullName>ProductFamily__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RelatedOptionalEquipment__c.field-meta.xml
<CustomField>
    <fullName>RelatedOptionalEquipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Optional Equipment</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Quote Line Items (Related Optional Equipment)</relationshipLabel>
    <relationshipName>QuoteLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RowDiscount__c.field-meta.xml
<CustomField>
    <fullName>RowDiscount__c</fullName>
    <label>Row Discount</label>
    <precision>15</precision>
    <scale>12</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RowNumber__c.field-meta.xml
<CustomField>
    <fullName>RowNumber__c</fullName>
    <label>Row Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RowTotalPrice__c.field-meta.xml
<CustomField>
    <fullName>RowTotalPrice__c</fullName>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/QuoteLineSubItem__c.object-meta.xml
<CustomObject>
    <label>Quote Line Sub Item</label>
    <nameField>
        <label>Quote Line Sub Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Sub Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLineSubItem__c/fields/IsVisible__c.field-meta.xml
<CustomField>
    <fullName>IsVisible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/fields/IsVisibleOnPDF__c.field-meta.xml
<CustomField>
    <fullName>IsVisibleOnPDF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visibel On PDF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/fields/Product2Id__c.field-meta.xml
<CustomField>
    <fullName>Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Sub Items</relationshipLabel>
    <relationshipName>Quote_Line_Sub_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/fields/ProductDescriptionCZ__c.field-meta.xml
<CustomField>
    <fullName>ProductDescriptionCZ__c</fullName>
    <label>Product Description CZ</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/fields/ProductDescriptionEN__c.field-meta.xml
<CustomField>
    <fullName>ProductDescriptionEN__c</fullName>
    <label>Product Description EN</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/fields/QuoteLineItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItemId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Quote Line Sub Items</relationshipLabel>
    <relationshipName>QuoteLineSubItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/fields/SortNumber__c.field-meta.xml
<CustomField>
    <fullName>SortNumber__c</fullName>
    <formula>/*CASE( Type__c,
&apos;Látka&apos;, 1,
&apos;Látka sezení&apos;, 2,
&apos;Látka polštáře&apos;, 3,
&apos;Počet modulů&apos;, 4,
&apos;Prosklený strop&apos;, 5,
&apos;Rám&apos;, 6,
&apos;Madlo&apos;, 7,
&apos;Panty&apos;, 8,
&apos;Výška stolu&apos;, 9,
&apos;Zásuvka&apos;, 10,
&apos;Vybavení&apos;, 11,
&apos;Doprava&apos;, 12,
&apos;Montáž&apos;, 13,
&apos;Balení&apos;, 14,
15)
*/
1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sort Number</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/QuotePdfController.cls
public with sharing class QuotePdfController {

    private final Quote quote;
    public User currentUser { get; set; }
    public QuoteLineItem[] qlis { get; set; }
    public Mdl.QuoteLineItemMdl[] qlisProd { get; set; }
    public Mdl.QuoteLineItemMdl[] qlisTrans { get; set; }
    public String currentDate { get; set; }
    public Decimal totalPriceVal { get; set; }
    public Integer prodCount { get; set; }
    public String subTotalProd { get; set; }
    public String subTotalTrans { get; set; }
    public String quoteDiscount { get; set; }
    public String prodTotaWithAllDisc { get; set; }
    public String totalPrice { get; set; }
    public ContentDocumentLink[] cdls { get; set; }
    public String quoteCurrency { get; set; }
    public Boolean isDraft { get; set; }
    public Integer colspan { get; set; }

    // Number formating settings
    private final static Integer precision = 2;
    private final static String separator = ' ';
    private final static String decimalSeparator = ',';

    public QuotePdfController(ApexPages.StandardController stdc) {
        Id[] prodIds = new Id[]{
        };
        qlisProd = new Mdl.QuoteLineItemMdl[]{
        };
        qlisTrans = new Mdl.QuoteLineItemMdl[]{
        };
        Decimal subTotalProdVal = 0;
        Decimal subTotalTransVal = 0;
        Decimal prodTotaWithAllDiscVal = 0;
        totalPriceVal = 0;
        prodCount = 0;
        colspan = 4;

        String[] fieldsToAdd = new String[]{
                'Id', 'QuoteNumber', 'QuoteNo__c', 'Name', 'Language__c', 'QPdf_IsDisplayDiscount__c', 'QPdf_IsDisplayDiscountUnitPrice__c', 'QPdf_IsDisplayListPrice__c',
                'QPdf_IsDisplayQuoteTotalPrice__c', 'QPdf_IsDisplayQuoteDiscount__c', 'ShippingStreet', 'ShippingCity', 'QuoteDiscount__c', 'NeedApprove__c', 'IsApproved__c',
                'QPdf_IsDisplayQuoteSubtotalPrice__c', 'QPdf_IsDisplayProductSubtotal__c',
                'Account.Name',
                'Opportunity.Name',
                'Owner.Name',
                'TechnicianId__r.Name',
                'TechnicianUserId__r.Name',
                'Contact.Name', 'Contact.Email', 'Contact.MobilePhone'
        };

        if (!Test.isRunningTest()) {
            stdc.addFields(fieldsToAdd);
        }
        this.quote = (Quote) stdc.getRecord();

        if (!quote.QPdf_IsDisplayDiscount__c) {
            colspan--;
        }
        if (!quote.QPdf_IsDisplayDiscountUnitPrice__c) {
            colspan--;
        }
        if (!quote.QPdf_IsDisplayListPrice__c) {
            colspan--;
        }

        if (quote.NeedApprove__c && !quote.IsApproved__c) {
            isDraft = true;
        } else {
            isDraft = false;
        }
        System.debug('isDraft ' + isDraft);
        this.quoteCurrency = this.quote.CurrencyIsoCode;
        this.currentUser = [SELECT Name, Email, MobilePhone, CompanyName FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        System.debug('Current User ' + currentUser);
        this.qlis = [
                SELECT Discount, Subtotal, RowDiscount__c, RowTotalPrice__c, TotalPrice, ProductDescriptionCZ__c, ProductDescriptionEN__c, ListPrice, Quantity, ProductFamily__c, RowNumber__c, RelatedOptionalEquipment__c,
                        ProductName__c, CurrencyIsoCode, Description, Product2Id, Product2.BusinessName__c, Product2.BusinessNameEN__c, Product2.Name, Product2.Specification__c, UnitPrice__c, IsTransport__c, Product2.Type__c, IsShowInQuotePDF__c, CreatedDate, (SELECT Id, QuoteLineItemId__c, TitleCZ__c, TitleEN__c, DescriptionCZ__c, DescriptionEN__c, RowNumber__c FROM QLIDescriptions__r ORDER BY RowNumber__c), (
                        SELECT Id, Name, ProductName__c, Description__c, ProductDescriptionCZ__c, ProductDescriptionEN__c, Product2Id__r.BusinessName__c, Product2Id__r.BusinessNameEN__c, Product2Id__r.Name, Product2Id__r.Specification__c
                        FROM QuoteLineSubItems__r
                        WHERE IsVisible__c = TRUE AND IsVisibleOnPDF__c = TRUE
                        ORDER BY SortNumber__c
                )
                FROM QuoteLineItem
                WHERE QuoteId = :quote.Id
                ORDER BY RowNumber__c ASC
        ];

        Decimal tmpSubtotal = 0;
        Integer counter = 0;
        Boolean addLast = true;
        for (Integer i = 0; i < this.qlis.size(); i++) {
            if (qlis[i].IsTransport__c) {
                Mdl.QuoteLineItemMdl qlim = fillModel(qlis[i]);
                qlisTrans.add(qlim);
                subTotalTransVal += qlis[i].RowTotalPrice__c;
            } else {
                Mdl.QuoteLineItemMdl qlim = fillModel(qlis[i]);
                if (qlis[i].RelatedOptionalEquipment__c == null) {
                    if (tmpSubtotal == 0) {
                        counter++;
                        tmpSubtotal += qlis[i].RowTotalPrice__c;
                    } else {
                        Mdl.QuoteLineItemMdl qlimDelimiter = createDelimiter(tmpSubtotal, counter);
                        qlisProd.add(qlimDelimiter);
                        tmpSubtotal = qlis[i].RowTotalPrice__c;
                        counter = 1;
                    }
                } else {
                    counter++;
                    tmpSubtotal += qlis[i].RowTotalPrice__c;

                    // Add subtotal to last product
                    if (i == qlis.size() - 1) {
                        System.debug('LAST QLI ' + qlis[i].Product2.BusinessName__c);
                        Mdl.QuoteLineItemMdl qlimDelimiter = createDelimiter(tmpSubtotal, counter);
                        qlisProd.add(qlim);
                        qlisProd.add(qlimDelimiter);
                        addLast = false;
                    }
                }
                if (addLast) {
                    qlisProd.add(qlim);
                }
                subTotalProdVal += qlis[i].UnitPrice__c * qlis[i].Quantity;
                prodTotaWithAllDiscVal += qlis[i].RowTotalPrice__c;
                prodIds.add(qlis[i].Product2Id);
                prodCount++;
            }
        }
        totalPriceVal = subTotalTransVal + prodTotaWithAllDiscVal;
        subTotalProd = formatCurrency(subTotalProdVal, 0, true);
        quoteDiscount = formatPercent(quote.QuoteDiscount__c, 2, true);
        subTotalTrans = formatCurrency(subTotalTransVal, 0, true);
        totalPrice = formatCurrency(totalPriceVal, 0, true);
        prodTotaWithAllDisc = formatCurrency(prodTotaWithAllDiscVal, 0, true);
        Datetime currDateTime = Datetime.now();
        currentDate = currDateTime.format('dd.MM.YYYY');
        if (!Test.isRunningTest()) {
            if (prodIds.size() > 0) {
                this.cdls = [SELECT ContentDocument.LatestPublishedVersionId, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId IN :prodIds AND ContentDocument.Title = 'ProductImage'];
            }
        }
    }


    //===================================================================================================
    // HELPERS - HELPERS - HELPERS - HELPERS - HELPERS - HELPERS - HELPERS - HELPERS - HELPERS - HELPERS 
    //===================================================================================================   

    public Mdl.QuoteLineItemMdl createDelimiter(Decimal subtotal, Integer counter) {
        Mdl.QuoteLineItemMdl qlimDelimiter = new Mdl.QuoteLineItemMdl();
        qlimDelimiter.isDelimiter = true;
        qlimDelimiter.subtotal = formatCurrency(subtotal, 0, true);
        qlimDelimiter.showDelimiter = counter > 1;
        return qlimDelimiter;
    }

    public Mdl.QuoteLineItemMdl fillModel(QuoteLineItem qli) {


        Mdl.QuoteLineItemMdl qlim = new Mdl.QuoteLineItemMdl();
        qlim.Id = qli.Id;
        qlim.Product2Id = qli.Product2Id;
        if (quote.Language__c == 'cs') {
            qlim.ProductBusName = qli.Product2.BusinessName__c;
        } else if (quote.Language__c == 'en_US') {
            qlim.ProductBusName = qli.Product2.BusinessNameEN__c;
        }
        qlim.ProductType = qli.Product2.Type__c;
        qlim.ProductName = qli.Product2.Name;
        qlim.ProductFamily = qli.ProductFamily__c;
        qlim.ProductSpecification = qli.Product2.Specification__c;
        qlim.ProductDescriptionCZ = qli.ProductDescriptionCZ__c;
        qlim.ProductDescriptionEN = qli.ProductDescriptionEN__c;
        qlim.Description = qli.Description;
        qlim.Quantity = formatNumber(qli.Quantity, 0);
        qlim.ListPrice = formatCurrency(qli.ListPrice, 0, true);
        if (qli.IsTransport__c) {
            qlim.RowTotalPrice = formatCurrency((qli.UnitPrice__c * qli.Quantity), 0, true);
        } else {
            qlim.RowTotalPrice = formatCurrency(((qli.ListPrice * qli.Quantity) * (1 - qli.RowDiscount__c / 100)), 0, true);
        }

        qlim.RowDiscount = formatPercent(qli.RowDiscount__c, 2, true);
        qlim.DiscountUnitPrice = formatCurrency(qli.UnitPrice__c, 0, true);
        qlim.RelatedOptional = qli.RelatedOptionalEquipment__c;
        qlim.qliDescs = qli.QLIDescriptions__r;
        qlim.qlsis = qli.QuoteLineSubItems__r;

        // IsShowInQuotePDF__c default value was set to true but default value on old records was false
        qlim.showProduct = (qli.CreatedDate > Cst.VISIBLE_IN_PDF_DATE && qli.IsShowInQuotePDF__c == false) ? false : true;
        return qlim;
    }

    public String formatNumber(Decimal val, Integer scale) {
        return format(val, scale, false, false, false);
    }
    public String formatNumber(Double val, Integer scale) {
        return format((Decimal) val, scale, false, false, false);
    }
    public String formatPercent(Decimal val, Integer scale, Boolean addPercentSymbol) {
        return format(val, scale, false, false, addPercentSymbol);
    }
    public String formatCurrency(Decimal val, Integer scale, Boolean addCode) {
        return format(val, scale, true, addCode, false);
    }
    public String formatCurrency(Double val, Integer scale, Boolean addCode) {
        return format((Decimal) val, scale, true, addCode, false);
    }
    private String format(Decimal val, Integer scale, Boolean isCurrency, Boolean addCurrencyCode, Boolean addPercentSymbol) {
        if (val == null) val = 0;

        String result = '';
        String sVal = String.valueOf(val.setScale(scale)); // get absolute value
        Integer len = sVal.length();
        if (scale > 0) scale += 1; // reflect decimal separator
        Decimal absVal = Math.abs(val);
        if (absVal > 999999999) {
            result += sVal.substring(0, len - 9 - scale) + separator + sVal.substring(len - 9 - scale, len - 6 - scale) + separator + sVal.substring(len - 6 - scale, len - 3 - scale) + separator + sVal.substring(len - 3 - scale, len);
        } else if (absVal > 999999) {
            result += sVal.substring(0, len - 6 - scale) + separator + sVal.substring(len - 6 - scale, len - 3 - scale) + separator + sVal.substring(len - 3 - scale, len);
        } else if (absVal > 999) {
            result += sVal.substring(0, len - 3 - scale) + separator + sVal.substring(len - 3 - scale, len);
        } else {
            result += sVal;
        }

        String currencyName = '';
        switch on quoteCurrency {
            when 'CZK' {
                currencyName = 'Kč';
            }
            when 'USD' {
                currencyName = '$';
            }
            when 'EUR' {
                currencyName = '€';
            }
        }

        if (addCurrencyCode) {
            result += ' ' + currencyName;
        } else if (addPercentSymbol) {
            result += ' %';
        }

        result = result.replace('.', decimalSeparator);
        return result;
    }

    public String getProductListPriceSummary(QuoteLineItem qli, Decimal discountedPrice) {
        // All discounted if discount applied
        return formatCurrency(discountedPrice * qli.Quantity, precision, true) + ((qli.Quantity > 1) ? ' (' + formatNumber(qli.Quantity, 2) + 'x ' + formatCurrency(discountedPrice, precision, true) + ')' : '');
    }
}