force-app/main/default/objects/Product2/fields/RequestForTechnicianId__c.field-meta.xml
<CustomField>
    <fullName>RequestForTechnicianId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request For Technician</label>
    <referenceTo>RequestForTechnician__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <externalId>true</externalId>
    <label>SAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceCZK__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceCZK__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price CZK</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceEUR__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceEUR__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price EUR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RequestForTechnician__c/RequestForTechnician__c.object-meta.xml
<CustomObject>
    <label>Request For Technician</label>
    <nameField>
        <displayFormat>RFT-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request For Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RFTProductionControllerTest.cls
@isTest
public class RFTProductionControllerTest  {

	@IsTest
	public static void testMethods(){
		RequestForTechnician__c rft = new RequestForTechnician__c();	
		insert rft;
		Product2 prod = new Product2(Name='MICRO OFFICE',IsActive=true,ProductCode='ABCD',SAPId__c='A0123',UnitPriceCZK__c=1000,UnitPriceEUR__c=20, RequestForTechnicianId__c = rft.Id);
		insert prod;
		RFTProductListController.auraGetProds(rft.Id);
		RFTProductListController.auraDeleteProduct(rft.Id, prod.Id);
	}
}