force-app/main/default/objects/Product2/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <externalId>true</externalId>
    <label>SAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceCZK__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceCZK__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price CZK</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceEUR__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceEUR__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price EUR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/LineCost__c.field-meta.xml
<CustomField>
    <fullName>LineCost__c</fullName>
    <label>Line Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RowDiscount__c.field-meta.xml
<CustomField>
    <fullName>RowDiscount__c</fullName>
    <label>Row Discount</label>
    <precision>15</precision>
    <scale>12</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RowTotalPrice__c.field-meta.xml
<CustomField>
    <fullName>RowTotalPrice__c</fullName>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/QuoteLineSubItem__c.object-meta.xml
<CustomObject>
    <label>Quote Line Sub Item</label>
    <nameField>
        <label>Quote Line Sub Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Sub Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLineSubItem__c/fields/QuoteLineItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItemId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Quote Line Sub Items</relationshipLabel>
    <relationshipName>QuoteLineSubItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteCloneControllerTest.cls
@isTest 

public with sharing class QuoteCloneControllerTest {

    @isTest
    private static void auraGetOppCurrencyTest() {	
        Opportunity opp = new Opportunity(StageName='Qualification', Name='Opp Test', CloseDate=Date.newInstance(2019, 8, 24));
        insert opp;
        String qt2 = QuoteCloneController.auraGetOppCurrency(opp.Id);
    }

    @isTest
    private static void auraCloneTest(){
        Id pricebookId = Test.getStandardPricebookId();
        String currForTest = Cst.CURR_CZK;
        Product2 prod = new Product2(Name='MICRO OFFICE',IsActive=true,ProductCode='ABCD',SAPId__c='A0123',UnitPriceCZK__c=1000,UnitPriceEUR__c=20);
		insert prod;
        PricebookEntry pbe = [SELECT Id FROM PricebookEntry WHERE Product2Id=:prod.Id AND CurrencyIsoCode=:currForTest LIMIT 1];
		Product2 subProd = new Product2(Name='Cloth for MO',IsActive=true,ProductCode='CFMO',SAPId__c='A0456');
        insert subProd;
        Opportunity opp = new Opportunity(StageName='Qualification', Name='Opp Test', CloseDate=Date.newInstance(2019, 8, 24));
        insert opp;
        Quote qt = new Quote(Name='Quote Test', OpportunityId=opp.Id, Pricebook2Id = pricebookId);
		insert qt;
		QuoteLineItem qli = new QuoteLineItem(QuoteId=qt.Id, Quantity=10, UnitPrice=10, Product2Id=prod.Id, PricebookEntryId = pbe.Id, RowDiscount__c=0.00, RowTotalPrice__c=10, LineCost__c=10);
		insert qli;
		QuoteLineItem qli2 = new QuoteLineItem(QuoteId=qt.Id, Quantity=10, UnitPrice=10, RowTotalPrice__c = 10, Product2Id=prod.Id, PricebookEntryId = pbe.Id, RowDiscount__c=0.00, LineCost__c=10);
		insert qli2;
		QuoteLineSubItem__c qlsi = new QuoteLineSubItem__c(QuoteLineItemId__c=qli.Id);
		insert qlsi;
        String qt2 = QuoteCloneController.auraClone(qt.Id, opp.Id);
    }
    
}