force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M-AKU_PENA</fullName>
            </value>
            <value>
                <fullName>M-BARVY</fullName>
            </value>
            <value>
                <fullName>M-DROBNY_SPMAT</fullName>
            </value>
            <value>
                <fullName>M-ELEKTRO</fullName>
            </value>
            <value>
                <fullName>M-FUKUMA</fullName>
            </value>
            <value>
                <fullName>M-KOV</fullName>
            </value>
            <value>
                <fullName>M-KOVANI</fullName>
            </value>
            <value>
                <fullName>M-LATKA</fullName>
            </value>
            <value>
                <fullName>M-MICROOFFICE</fullName>
            </value>
            <value>
                <fullName>M-OBALY</fullName>
            </value>
            <value>
                <fullName>M-OSTATNI</fullName>
            </value>
            <value>
                <fullName>M-PLOSNY_MAT</fullName>
            </value>
            <value>
                <fullName>M-SKLO</fullName>
            </value>
            <value>
                <fullName>P-POLOTOVAR</fullName>
            </value>
            <value>
                <fullName>S-SKLADOVE SLUZBY</fullName>
            </value>
            <value>
                <fullName>S-SLUZBY</fullName>
            </value>
            <value>
                <fullName>V-VYROBEK</fullName>
            </value>
            <value>
                <fullName>Z-ZBOZI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SyncServiceSettings__c/SyncServiceSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SyncServiceSettings</label>
</CustomObject>

force-app/main/default/objects/SyncServiceSettings__c/fields/DisableSync__c.field-meta.xml
<CustomField>
    <fullName>DisableSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SpecificationPdfControllerTest.cls
@isTest
private class SpecificationPdfControllerTest {
	@isTest
    private static void SpecificationPdfControllerTest() {
    	SyncServiceSettings__c stt = new SyncServiceSettings__c();
        stt.Name = 'AccountToSAP';
        stt.DisableSync__c = true;
        insert stt;
        
        Opportunity opp = new Opportunity(StageName='Qualification', Name='Opp Test', CloseDate=Date.newInstance(2019, 8, 24));
        insert opp;
		Quote qt = new Quote(Name='Quote Test', OpportunityId=opp.Id);
        insert qt;
		
        Id pricebookId = Test.getStandardPricebookId();
        Product2 prod = new Product2(Name='Product', IsActive=true, Type__c = 'V-VYROBEK');
        insert prod;
        PricebookEntry pbe = [SELECT Id FROM PricebookEntry WHERE Product2Id=:prod.Id AND CurrencyIsoCode=:Cst.CURR_CZK AND IsActive=true LIMIT 1];
        
        QuoteLineItem qlis = new QuoteLineItem(QuoteId=qt.Id, PricebookEntryId=pbe.Id, Product2Id=prod.Id, Quantity=2, UnitPrice=100.00);
        insert qlis;
        
        ContentVersion cvOne = new ContentVersion(VersionData = Blob.valueOf('ngadgnk'), Title = 'Specification', PathOnClient = 'PathOnClient');
        insert cvOne;
        ContentVersion cvTwo = new ContentVersion(VersionData = Blob.valueOf('ngadgnk'), Title = 'SpecificationDetail', PathOnClient = 'PathOnClient');
        insert cvTwo;
        
        ContentDocument[] cDoc = [SELECT Id FROM ContentDocument LIMIT 2];
        
        ContentDocumentLink cdlOne = new ContentDocumentLink(ContentDocumentId=cDoc[0].Id, LinkedEntityId=prod.Id, ShareType='V', Visibility='AllUsers');
        insert cdlOne;
        ContentDocumentLink cdlTwo = new ContentDocumentLink(ContentDocumentId=cDoc[1].Id, LinkedEntityId=prod.Id, ShareType='V', Visibility='AllUsers');
        insert cdlTwo;
        
        ApexPages.StandardController stdCtrl = new ApexPages.StandardController(qt);
        SpecificationPdfController ctrl = new SpecificationPdfController(stdCtrl);
    } 
}