force-app/main/default/objects/Account/fields/AccountEId__c.field-meta.xml
<CustomField>
    <fullName>AccountEId__c</fullName>
    <externalId>true</externalId>
    <label>Account EID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CanceledInvoiceId__c.field-meta.xml
<CustomField>
    <fullName>CanceledInvoiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to Invoice which is cancelled by current Invoice</description>
    <inlineHelpText>Relation to Invoice which is cancelled by current Invoice</inlineHelpText>
    <label>Canceled Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Cancel Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CanceledInvoiceSAPId__c.field-meta.xml
<CustomField>
    <fullName>CanceledInvoiceSAPId__c</fullName>
    <description>SAP ID of Invoice which is cancelled by current Invoice</description>
    <inlineHelpText>SAP ID of Invoice which is cancelled by current Invoice</inlineHelpText>
    <label>Canceled Invoice SAP ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <externalId>true</externalId>
    <label>SAP ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SyncServiceSettings__c/SyncServiceSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SyncServiceSettings</label>
</CustomObject>

force-app/main/default/objects/SyncServiceSettings__c/fields/DisableSync__c.field-meta.xml
<CustomField>
    <fullName>DisableSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SyncServiceSettings__c/fields/ForceStatusCode__c.field-meta.xml
<CustomField>
    <fullName>ForceStatusCode__c</fullName>
    <description>Used for Response Status Code manual setup - it has no consequence wit the service run - it will always end with this status (direction TO SF ONLY)</description>
    <inlineHelpText>Used for Response Status Code manual setup - it has no consequence wit the service run - it will always end with this status (direction TO SF ONLY)</inlineHelpText>
    <label>Force Status Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Svc_InvoiceToSF.cls
@RestResource(urlMapping='/sync/invoice')
global without sharing class Svc_InvoiceToSF{
    private static String SVC_NAME = 'InvoiceToSF';
    private static SyncServiceSettings__c stt = SyncServiceSettings__c.getValues(SVC_NAME);
    // https://<org-domain>/services/apexrest/sync/invoice
        
    @HttpPost
    global static void doPost() {
        if(stt.DisableSync__c){ SyncUtils.logServiceActivity(SVC_NAME, Cst.STATUS_ERROR, 503, 'ERROR: Service is disabled'); return; }

        // Get valid settings
        String validToken = 'Baerer '+stt.Token__c;
        // Also for testing
        if(Test.isRunningTest()){ validToken = 'Baerer '+'XXXXX'; }

        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;

        String token = req.headers.get('token');
        String body = (req.requestBody != null) ? req.requestBody.toString() : '';
        System.debug('body: '+body);

        // Validate token
        if(String.isEmpty(token) || token != validToken){
            res.statusCode = 401;
            res.responseBody = Blob.valueOf('Invalid token - requested ('+token+')');
            return;
        }

        // Insert inbound records - lsit of Orders
        String msg = 'SUSCCESS: Invoices synced.';
        String stackTrace = '';
        String errStr = '';
        String status = Cst.STATUS_SUCCESS;
        res.statusCode = 200;
        try{
			Invoice__c[] invcsToUpsert = new Invoice__c[]{};
            Invoice__c[] recs = (Invoice__c[])JSON.deserialize(body, Invoice__c[].class);
            Set<String> accIdsSet = new Set<String>();
            Set<String> invIdsSet = new Set<String>();
            for(Invoice__c r : recs){
                accIdsSet.add(r.AccountId__c);
                if(String.isNotEmpty(r.CanceledInvoiceSAPId__c)){
                    invIdsSet.add(r.CanceledInvoiceSAPId__c);
                }
            }
            
			// Get related data
			Account[] accs = [SELECT Id,AccountEID__c FROM Account WHERE AccountEID__c IN: accIdsSet];
            Map<String,String> accMap = new Map<String,String>();
            for(Account a : accs){
                accMap.put(a.AccountEID__c,a.Id);
            }
            Invoice__c[] exInvcs = [SELECT Id,SAPId__c FROM Invoice__c WHERE SAPId__c IN: invIdsSet];
            Map<String,String> invMap = new Map<String,String>();
            for(Invoice__c inv : exInvcs){
                invMap.put(inv.SAPId__c,inv.Id);
            }

			// Invoice data
            for(Invoice__c r : recs){
                r.AccountId__c = accMap.get(r.AccountId__c); // Assign SF IDs
                if(String.isNotEmpty(r.CanceledInvoiceSAPId__c)){
                    r.CanceledInvoiceId__c = invMap.get(r.CanceledInvoiceSAPId__c);
                }
			}
            Database.UpsertResult[] srs = Database.upsert(recs, Invoice__c.SAPId__c.getDescribe().getSObjectField(), false);
			for(Integer i=0; i<srs.size();i++){
				if(!srs[i].isSuccess()){
                    errStr += 'ERROR: '+srs[i].getErrors()+'\n\n'+'RECORD: '+JSON.serializePretty(recs[i]+'\n\n');
				}
			}
            if(String.isNotEmpty(errStr)){
                stackTrace += '\n'+errStr;
                status = Cst.STATUS_WARNING;
            }
        }catch(Exception e){
            status = Cst.STATUS_ERROR;
            res.statusCode = 400;
            msg = e.getMessage();
			stackTrace = e.getStackTraceString();
			res.responseBody = Blob.valueOf(msg+'\n'+stackTrace);
        }

		// Force set Response Status by settings
		if(stt.ForceStatusCode__c != null){ res.statusCode = (Integer)stt.ForceStatusCode__c; msg = 'FORCED STATUS CODE:\n'+msg; }

        SyncUtils.logServiceActivity(SVC_NAME, status, res.statusCode, msg, stackTrace, Hlp.getStringWithLength(body,32000));
        return;
    }
}