force-app/main/default/objects/Account/fields/DiscountAccount__c.field-meta.xml
<CustomField>
    <fullName>DiscountAccount__c</fullName>
    <label>Account Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en_US</fullName>
                <label>EN</label>
            </value>
            <value>
                <fullName>cs</fullName>
                <label>CS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent ID</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ProjectSalesFee__c.field-meta.xml
<CustomField>
    <fullName>ProjectSalesFee__c</fullName>
    <label>Project Sales Fee</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ProjectSalesFeeValue__c.field-meta.xml
<CustomField>
    <fullName>ProjectSalesFeeValue__c</fullName>
    <label>Project Sales Fee Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QPdf_IsDisplayDiscount__c.field-meta.xml
<CustomField>
    <fullName>QPdf_IsDisplayDiscount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Discount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QPdf_IsDisplayDiscountUnitPrice__c.field-meta.xml
<CustomField>
    <fullName>QPdf_IsDisplayDiscountUnitPrice__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Display Unit Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QPdf_IsDisplayListPrice__c.field-meta.xml
<CustomField>
    <fullName>QPdf_IsDisplayListPrice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display List Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QPdf_IsDisplayProductSubtotal__c.field-meta.xml
<CustomField>
    <fullName>QPdf_IsDisplayProductSubtotal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Product Subtotal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QPdf_IsDisplayQuoteDiscount__c.field-meta.xml
<CustomField>
    <fullName>QPdf_IsDisplayQuoteDiscount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Quote Discount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QPdf_IsDisplayQuoteSubtotalPrice__c.field-meta.xml
<CustomField>
    <fullName>QPdf_IsDisplayQuoteSubtotalPrice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Quote Subtotal Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QPdf_IsDisplayQuoteTotalPrice__c.field-meta.xml
<CustomField>
    <fullName>QPdf_IsDisplayQuoteTotalPrice__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Quote Total Price</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QuoteDiscount__c.field-meta.xml
<CustomField>
    <fullName>QuoteDiscount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quote Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QuoteDiscountValue__c.field-meta.xml
<CustomField>
    <fullName>QuoteDiscountValue__c</fullName>
    <label>Quote Discount Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QuoteTotalDiscount__c.field-meta.xml
<CustomField>
    <fullName>QuoteTotalDiscount__c</fullName>
    <label>Quote Total Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <label>Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if QLI is standard product without changes in the BOM structure</description>
    <inlineHelpText>Determines if QLI is standard product without changes in the BOM structure</inlineHelpText>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IsTransport__c.field-meta.xml
<CustomField>
    <fullName>IsTransport__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if row is specific type of Transport.</description>
    <inlineHelpText>Determines if row is specific type of Transport.</inlineHelpText>
    <label>Transport</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/LineCost__c.field-meta.xml
<CustomField>
    <fullName>LineCost__c</fullName>
    <label>Line Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>QuoteLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProductFamily__c.field-meta.xml
<CustomField>
    <fullName>ProductFamily__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/QuantityUnitOfMeasure__c.field-meta.xml
<CustomField>
    <fullName>QuantityUnitOfMeasure__c</fullName>
    <formula>TEXT(Product2.QuantityUnitOfMeasure)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity Unit Of Measure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RelatedOptionalEquipment__c.field-meta.xml
<CustomField>
    <fullName>RelatedOptionalEquipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Optional Equipment</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Quote Line Items (Related Optional Equipment)</relationshipLabel>
    <relationshipName>QuoteLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RowDiscount__c.field-meta.xml
<CustomField>
    <fullName>RowDiscount__c</fullName>
    <label>Row Discount</label>
    <precision>15</precision>
    <scale>12</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RowNumber__c.field-meta.xml
<CustomField>
    <fullName>RowNumber__c</fullName>
    <label>Row Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RowTotalDiscount__c.field-meta.xml
<CustomField>
    <fullName>RowTotalDiscount__c</fullName>
    <label>Row Total Discount</label>
    <precision>15</precision>
    <scale>12</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RowTotalPrice__c.field-meta.xml
<CustomField>
    <fullName>RowTotalPrice__c</fullName>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TC_AccommodationCost__c.field-meta.xml
<CustomField>
    <fullName>TC_AccommodationCost__c</fullName>
    <description>Part of Transportation Cost. Always in CZK.</description>
    <inlineHelpText>Part of Transportation Cost. Always in CZK.</inlineHelpText>
    <label>Accommodation Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TC_AssemblyCost__c.field-meta.xml
<CustomField>
    <fullName>TC_AssemblyCost__c</fullName>
    <description>Part of Transportation Cost. Always in CZK.</description>
    <inlineHelpText>Part of Transportation Cost. Always in CZK.</inlineHelpText>
    <label>Assembly Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TC_MaterialShippingCost__c.field-meta.xml
<CustomField>
    <fullName>TC_MaterialShippingCost__c</fullName>
    <description>Part of Transport Cost. Always in CZK.</description>
    <inlineHelpText>Part of Transport Cost. Always in CZK.</inlineHelpText>
    <label>Material Shipping Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/TC_ShippingCost__c.field-meta.xml
<CustomField>
    <fullName>TC_ShippingCost__c</fullName>
    <description>Part of Transport Cost. Always in CZK.</description>
    <inlineHelpText>Part of Transport Cost. Always in CZK.</inlineHelpText>
    <label>Shipping Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/QuoteLineSubItem__c.object-meta.xml
<CustomObject>
    <label>Quote Line Sub Item</label>
    <nameField>
        <label>Quote Line Sub Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Sub Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLineSubItem__c/fields/ProductDescriptionCZ__c.field-meta.xml
<CustomField>
    <fullName>ProductDescriptionCZ__c</fullName>
    <label>Product Description CZ</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/fields/ProductDescriptionEN__c.field-meta.xml
<CustomField>
    <fullName>ProductDescriptionEN__c</fullName>
    <label>Product Description EN</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/fields/QuantityUnitOfMeasure__c.field-meta.xml
<CustomField>
    <fullName>QuantityUnitOfMeasure__c</fullName>
    <formula>TEXT( Product2Id__r.QuantityUnitOfMeasure )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity Unit Of Measure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuoteCloneController.cls
public without sharing class QuoteCloneController {
    
    
    @AuraEnabled
    public static String auraGetOppCurrency(String oppId){
        return [SELECT CurrencyIsoCode FROM Opportunity WHERE Id =: oppId LIMIT 1].CurrencyIsoCode;
    }

    @AuraEnabled
    public static String auraClone(String quoteId, String oppId){
        // Savepoint sp = Database.setSavepoint();
        // try {
            Opportunity opp = [SELECT Account.DiscountAccount__c, Street__c, City__c, PostalCode__c, Country__c, State__c, CurrencyIsoCode, Account.BillingStreet, Account.BillingCity, Account.BillingCountry, Account.BillingPostalCode, Account.BillingState FROM Opportunity WHERE Id =: oppId LIMIT 1];
            Decimal newAccDiscount = (opp.Account.DiscountAccount__c != null && opp.Account.DiscountAccount__c > 0) ? opp.Account.DiscountAccount__c + 0 : 0;
            Quote originalQuote = [SELECT Id, Phone, Description__c, Description, Discount, Email, GrandTotal, Language__c, QuoteDiscount__c, 
                                    QuoteDiscountValue__c, QuoteToAddress, QuoteTotalDiscount__c, Subtotal__c, TotalPrice__c, ProjectSalesFee__c, ProjectSalesFeeValue__c, ContactId,
                                    QPdf_IsDisplayQuoteTotalPrice__c, QPdf_IsDisplayQuoteSubtotalPrice__c, QPdf_IsDisplayQuoteDiscount__c, QPdf_IsDisplayProductSubtotal__c, QPdf_IsDisplayListPrice__c,
                                    QPdf_IsDisplayDiscountUnitPrice__c, QPdf_IsDisplayDiscount__c
                                    FROM Quote WHERE Id =: quoteId LIMIT 1];
            QuoteLineItem[] qlis = [SELECT Id, PricebookEntryId, TC_AccommodationCost__c, TC_AssemblyCost__c, ServiceDate, IsDefault__c, Discount, LineCost__c, Description, ListPrice, TC_MaterialShippingCost__c,
                                    ParentId__c, Product2Id, ProductDescriptionEN__c, ProductDescriptionCZ__c, ProductFamily__c, ProductName__c, Quantity, QuantityUnitOfMeasure__c, RowDiscount__c, CreatedDate,
                                    RowNumber__c, RowTotalDiscount__c, UnitPrice, TC_ShippingCost__c, Subtotal, RowTotalPrice__c, TotalPrice, IsTransport__c, UnitPrice__c, RelatedOptionalEquipment__c, IsShowInQuotePDF__c
                                    FROM QuoteLineItem WHERE QuoteId =: quoteId];

            // Get All QLI Ids
            // If any QLI has greater discount
            Set<Id> qliIds = new Set<Id>();
            Boolean greaterDiscount = false;
            Decimal tmpSubtotal = 0;
            for(QuoteLineItem qli : qlis){
                qliIds.add(qli.Id);
                if(!qli.IsTransport__c){
                    System.debug('Testing ' + qli.RowDiscount__c + ', ' + newAccDiscount);
                    tmpSubtotal += (qli.ListPrice * qli.Quantity) * (1 - (((qli.RowDiscount__c > newAccDiscount) ? newAccDiscount : qli.RowDiscount__c) / 100));
                }
                if(qli.RowTotalDiscount__c > newAccDiscount){
                    greaterDiscount = true;
                }
            }

            // Get All Quote Line Sub Items associated with qlis
            QuoteLineSubItem__c[] qlsis = [SELECT Id, Description__c, IsEditable__c, OwnerId, Position__c, Product2Id__c, ProductBusinessName__c, ProductDescriptionCZ__c, ProductDescriptionEN__c, ProductName__c,
                                    Quantity__c, QuantityUnitOfMeasure__c, Name, SortNumber__c, IsTemplateProduct__c, IsVisible__c, IsVisibleOnPDF__c, QuoteLineItemId__c 
                                    FROM QuoteLineSubItem__c WHERE QuoteLineItemId__c IN: qliIds];
            
            Map<Id, QuoteLineSubItem__c[]> qlsiByQLIId = new Map<Id, QuoteLineSubItem__c[]>();
            for(QuoteLineSubItem__c qlsi : qlsis){
                QuoteLineSubItem__c[] tmp = qlsiByQLIId.get(qlsi.QuoteLineItemId__c);
                if(tmp == null){
                    tmp = new QuoteLineSubItem__c[]{};
                    qlsiByQLIId.put(qlsi.QuoteLineItemId__c, tmp);
                }
                tmp.add(qlsi);
            }
            
            // Get All Quote Line Descriptions associated with qlis
            QLIDescription__c[] qliDescs = [SELECT DescriptionCZ__c, DescriptionEN__c, Name, OwnerId, RowNumber__c, TitleCZ__c, TitleEN__c, QuoteLineItemId__c 
                                            FROM QLIDescription__c WHERE QuoteLineItemId__c IN: qliIds];
            
            Map<Id, QLIDescription__c[]> qlidByQLIId = new Map<Id, QLIDescription__c[]>();
            for(QLIDescription__c qlid : qliDescs){
                QLIDescription__c[] tmp = qlidByQLIId.get(qlid.QuoteLineItemId__c);
                if(tmp == null){
                    tmp = new QLIDescription__c[]{};
                    qlidByQLIId.put(qlid.QuoteLineItemId__c, tmp);
                }
                tmp.add(qlid);
            }
                                    
            System.debug('QLIS ' + qlis);

            // Clone Quote
            Quote clonedQuote = originalQuote.clone(false, true, false, false);
            if(greaterDiscount){
                clonedQuote.QuoteDiscount__c = 0;
                clonedQuote.QuoteDiscountValue__c = 0;
                clonedQuote.Subtotal__c = tmpSubtotal;
            }

            clonedQuote.IsCloned__c = true;
            clonedQuote.Status = 'Processed';
            clonedQuote.OpportunityId = oppId;
            clonedQuote.ParentId__c = quoteId;
            clonedQuote.IsSendAddressToOpportunity__c = false;

            clonedQuote.ShippingStreet = opp.Street__c;
            clonedQuote.ShippingCity = opp.City__c;
            clonedQuote.ShippingPostalCode = opp.PostalCode__c;
            clonedQuote.ShippingCountry = opp.Country__c;

            clonedQuote.BillingCity = opp.Account.BillingCity;
            clonedQuote.BillingCountry = opp.Account.BillingCountry;
            clonedQuote.BillingPostalCode = opp.Account.BillingPostalCode;
            clonedQuote.BillingState = opp.Account.BillingState;
            clonedQuote.BillingStreet = opp.Account.BillingStreet;
            insert clonedQuote;

            // Clone RFT & RFTLink
            RequestForTechnicianLink__c[] rftLinks = new RequestForTechnicianLink__c[]{};
            RequestForTechnician__c[] quoteRFTs = [SELECT Id, QuoteId__c FROM RequestForTechnician__c WHERE QuoteId__c =: originalQuote.Id];
            if(quoteRFTs.size() > 0){
                for(RequestForTechnician__c rft : quoteRFTs){
                    rftLinks.add(new RequestForTechnicianLink__c(QuoteId__c = clonedQuote.Id, RequestForTechnicianId__c = rft.Id));
                }
            }
            
            RequestForTechnicianLink__c[] quoteRFTLinks = [SELECT Id, QuoteId__c, RequestForTechnicianId__c FROM RequestForTechnicianLink__c WHERE QuoteId__c =: originalQuote.Id];
            if(quoteRFTLinks.size() > 0){
                for(RequestForTechnicianLink__c originalRFTLink : quoteRFTLinks){
                    RequestForTechnicianLink__c clonedRFTLink = originalRFTLink.clone(false, true, false, false);
                    clonedRFTLink.QuoteId__c = clonedQuote.Id;
                    rftLinks.add(clonedRFTLink);
                }
            }

            if(rftLinks.size() > 0){
                insert rftLinks;
            }
            
            // Clone QLI
            Decimal qtTotalPrice = 0;
            Decimal qtTotalListPrice = 0;
            Decimal qtTotalPriceWithTrans = 0;
            Decimal totalLineCost = 0;
            QuoteLineItem[] clonedQLIs = new QuoteLineItem[]{};
            for(QuoteLineItem originalQLI : qlis){
                totalLineCost += originalQLI.LineCost__c;
                QuoteLineItem clonedQLI = originalQLI.clone(false, true, false, false);
                if(originalQLI.CreatedDate < Cst.VISIBLE_IN_PDF_DATE){
                    clonedQLI.IsShowInQuotePDF__c = true;
                }
                if(clonedQLI.RowTotalDiscount__c > newAccDiscount && !clonedQLI.IsTransport__c){
                    System.debug('NewAcc Discount ' + newAccDiscount);
                    clonedQLI.RowTotalDiscount__c = newAccDiscount;
                    clonedQLI.UnitPrice = clonedQLI.ListPrice * (1 - (clonedQLI.RowTotalDiscount__c / 100));
                }
                if(clonedQLI.RowDiscount__c > newAccDiscount && !clonedQLI.IsTransport__c){
                    clonedQLI.RowDiscount__c = newAccDiscount;
                    clonedQLI.UnitPrice__c = clonedQLI.ListPrice * (1 - (clonedQLI.RowDiscount__c / 100));
                    clonedQLI.RowTotalPrice__c = (clonedQLI.ListPrice * clonedQLI.Quantity) * (1 - (clonedQLI.RowDiscount__c / 100));
                }

                clonedQLI.OriginId__c = originalQLI.Id;
                clonedQLI.QuoteId = clonedQuote.Id;
                clonedQLIs.add(clonedQLI);

                // Prepare values for QT
                if(!clonedQLI.IsTransport__c){
                    qtTotalPrice += clonedQLI.RowTotalPrice__c;
                    qtTotalListPrice += (clonedQLI.ListPrice * clonedQLI.Quantity);
                }
                qtTotalPriceWithTrans += clonedQLI.RowTotalPrice__c;
            }

            
            insert clonedQLIs;

            // Add Lookup RelatedOptionalEquipment
            for(QuoteLineItem clonedQLIOrigin : clonedQLIs){
                for(QuoteLineItem clonedQLI : clonedQLIs){
                    if(!String.isBlank(clonedQLI.RelatedOptionalEquipment__c) && clonedQLI.RelatedOptionalEquipment__c == clonedQLIOrigin.OriginId__c){
                        clonedQLI.RelatedOptionalEquipment__c = clonedQLIOrigin.Id;
                    }
                }
            }
            update clonedQLIs;
            
            clonedQuote.TotalPrice__c = qtTotalPriceWithTrans;
            clonedQuote.QuoteTotalDiscount__c = (qtTotalListPrice == 0) ? 0 :(1 - (qtTotalPrice / qtTotalListPrice)) * 100;
            for(ProjectSalesFee__c psf: [SELECT Id, LowerRange__c, HigherRange__c, Reward__c FROM ProjectSalesFee__c]){
                Decimal quoteTotalDisc = clonedQuote.QuoteTotalDiscount__c.setScale(2);
                if(psf.LowerRange__c >= quoteTotalDisc && psf.HigherRange__c <= quoteTotalDisc){
                    Decimal czkTotalPrice = Hlp.getDatedCZKValue(clonedQuote.TotalPrice__c, opp.CurrencyIsoCode, Date.today());
                    clonedQuote.ProjectSalesFee__c = psf.Reward__c;
                    clonedQuote.ProjectSalesFeeValue__c = (czkTotalPrice - totalLineCost) * (psf.Reward__c / 100);
                    break;
                }
            }
            update clonedQuote;

            // Clone QLSI
            if(clonedQLIs.size() > 0){
                QuoteLineSubItem__c[] clonedQLSIs = new QuoteLineSubItem__c[]{};
                QLIDescription__c[] clonedQLIDs = new QLIDescription__c[]{};
                for(QuoteLineItem clonedQLI : clonedQLIs){
                    if(qlsiByQLIId.get(clonedQLI.OriginId__c) != null){
                        System.debug('qlsiByQLIId '+ qlsiByQLIId.get(clonedQLI.OriginId__c));
                        for(QuoteLineSubItem__c originalQLSI : qlsiByQLIId.get(clonedQLI.OriginId__c)){
                            QuoteLineSubItem__c clonedQLSI = originalQLSI.clone(false, true, false, false);
                            clonedQLSI.QuoteLineItemId__c = clonedQLI.Id;
                            clonedQLSIs.add(clonedQLSI);
                        }
                    }
                    if(qlidByQLIId.get(clonedQLI.OriginId__c) != null){
                        System.debug('qlsiByQLIId '+ qlidByQLIId.keySet());
                        for(QLIDescription__c originalQLID : qlidByQLIId.get(clonedQLI.OriginId__c)){
                            QLIDescription__c clonedQLID = originalQLID.clone(false, true, false, false);
                            clonedQLID.QuoteLineItemId__c = clonedQLI.Id;
                            clonedQLIDs.add(clonedQLID);
                        }
                    }
                }
                insert clonedQLSIs;
                insert clonedQLIDs;
            }
            

            return clonedQuote.Id;
        // } catch (Exception e) {
        //     Database.rollback(sp);
        //     throw new AuraHandledException(e.getMessage());
        // }
    }
}