force-app/main/default/objects/Account/fields/FinalInvoicePaymentTerm__c.field-meta.xml
<CustomField>
    <fullName>FinalInvoicePaymentTerm__c</fullName>
    <label>Final Invoice Payment Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Invoicing_Department_Acc__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Department_Acc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Invoicing_Department_Acc</description>
    <inlineHelpText>Kontaktní osoba fakturace</inlineHelpText>
    <label>Invoicing Department</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ProformaPaymentTerm__c.field-meta.xml
<CustomField>
    <fullName>ProformaPaymentTerm__c</fullName>
    <label>Proforma Payment Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/ProformaPercent_Acc__c.field-meta.xml
<CustomField>
    <fullName>ProformaPercent_Acc__c</fullName>
    <inlineHelpText>Procento zálohové platby</inlineHelpText>
    <label>Proforma %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contact_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FinalInvoicePaymentTerm__c.field-meta.xml
<CustomField>
    <fullName>FinalInvoicePaymentTerm__c</fullName>
    <label>Final Invoice Payment Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoicing_Department__c.field-meta.xml
<CustomField>
    <fullName>Invoicing_Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Kontaktní osoba fakturace</inlineHelpText>
    <label>Invoicing Department</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Invoicing Department)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PaymentTerm__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerm__c</fullName>
    <label>Proforma Payment Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProformaPercent__c.field-meta.xml
<CustomField>
    <fullName>ProformaPercent__c</fullName>
    <label>Proforma %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/globalValueSets/Contact_Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Dealer</fullName>
    </customValue>
    <customValue>
        <fullName>End user</fullName>
    </customValue>
    <masterLabel>Contact Role</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityTriggerServiceTest.cls
/**
 * Created by David Martinka on 10.01.2023.
 * Mooza Inspire s.r.o.
 */
@IsTest
public with sharing class OpportunityTriggerServiceTest {
    @IsTest
    static void should_populateFieldsFromAccount_when_beforeInsertTest() {
        Account invoicingDepartmentAccount = new Account(Name = 'Invoicing Department Account', BillingCity = 'City', BillingCountry = 'Czech Republic', BillingStreet = 'Street');
        insert invoicingDepartmentAccount;

        Account account = new Account(
                Name = 'Test Account',
                ProformaPaymentTerm__c = 50,
                FinalInvoicePaymentTerm__c = 50,
                ProformaPercent_Acc__c = 50.25,
                BillingCity = 'City',
                BillingCountry = 'Czech Republic',
                BillingStreet = 'Street'
        );
        insert account;

        Contact invoicingDepartmentContact = new Contact(FirstName = 'Contact', LastName = 'Test', Email = 'invocing@department-contact.com', Role__c='End user');
        insert invoicingDepartmentContact;

        account.Invoicing_Department_Acc__c = invoicingDepartmentContact.Id;
        update account;

        insert new Opportunity(Name = 'Testing Opportunity', AccountId = account.Id, CloseDate = System.today().addMonths(12), StageName = 'Qualification');

        List<Opportunity> opportunities = [SELECT Id, PaymentTerm__c, FinalInvoicePaymentTerm__c, Invoicing_Department__c, ProformaPercent__c FROM Opportunity WHERE Name = 'Testing Opportunity'];
        System.assertEquals(opportunities.get(0).PaymentTerm__c, account.ProformaPaymentTerm__c, 'This field should be automatically populated by before insert trigger from Account');
        System.assertEquals(opportunities.get(0).FinalInvoicePaymentTerm__c, account.FinalInvoicePaymentTerm__c, 'This field should be automatically populated by before insert trigger from Account');
        System.assertEquals(opportunities.get(0).Invoicing_Department__c, account.Invoicing_Department_Acc__c, 'This field should be automatically populated by before insert trigger from Account');
        System.assertEquals(opportunities.get(0).ProformaPercent__c, account.ProformaPercent_Acc__c, 'This field should be automatically populated by before insert trigger from Account');
    }
}