force-app/main/default/objects/Account/fields/IsValidated__c.field-meta.xml
<CustomField>
    <fullName>IsValidated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field says whether was account validated in SAP.</description>
    <inlineHelpText>This field says whether was account validated in SAP.</inlineHelpText>
    <label>Validated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/VatNo__c.field-meta.xml
<CustomField>
    <fullName>VatNo__c</fullName>
    <inlineHelpText>IČ</inlineHelpText>
    <label>IČ</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/BOM__c.object-meta.xml
<CustomObject>
    <description>Bill Of Material</description>
    <label>BOM</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BOM__c/fields/BundleId__c.field-meta.xml
<CustomField>
    <fullName>BundleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to bundle master product.</description>
    <inlineHelpText>Relation to bundle master product.</inlineHelpText>
    <label>Bundle</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Items (list of material)</relationshipLabel>
    <relationshipName>BOMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/BundleItemId__c.field-meta.xml
<CustomField>
    <fullName>BundleItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to bundle item product.</description>
    <inlineHelpText>Relation to bundle item product.</inlineHelpText>
    <label>Bundle Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parent Bundles (where is this material used)</relationshipLabel>
    <relationshipName>BOMItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantity in Bundle.</description>
    <inlineHelpText>Quantity in Bundle.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <label>SAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contact_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <externalId>true</externalId>
    <label>SAP ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OrderDueDate__c.field-meta.xml
<CustomField>
    <fullName>OrderDueDate__c</fullName>
    <description>Due Date is required in SAP (means due date for realization)</description>
    <inlineHelpText>= Realization Start; Due Date is required in SAP (means due date for realization)</inlineHelpText>
    <label>Order Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Realisation_Start_confirmed__c.field-meta.xml
<CustomField>
    <fullName>Realisation_Start_confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Please, update the Realisation Start Date, or mark the date as confirmed</inlineHelpText>
    <label>Realisation Start confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RealizationEndDate__c.field-meta.xml
<CustomField>
    <fullName>RealizationEndDate__c</fullName>
    <label>Realization End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RealizationStartDate__c.field-meta.xml
<CustomField>
    <fullName>RealizationStartDate__c</fullName>
    <label>Realization Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/RealizationEndDate__c.field-meta.xml
<CustomField>
    <fullName>RealizationEndDate__c</fullName>
    <label>Realization End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/RealizationStartDate__c.field-meta.xml
<CustomField>
    <fullName>RealizationStartDate__c</fullName>
    <label>Realization Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/ShippingAddressTxt__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddressTxt__c</fullName>
    <label>Shipping Address (txt)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/RequestForTechnicianId__c.field-meta.xml
<CustomField>
    <fullName>RequestForTechnicianId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request For Technician</label>
    <referenceTo>RequestForTechnician__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <externalId>true</externalId>
    <label>SAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceCZK__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceCZK__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price CZK</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceEUR__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceEUR__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price EUR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DescriptionForTechnician__c.field-meta.xml
<CustomField>
    <fullName>DescriptionForTechnician__c</fullName>
    <label>Description for Technician</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/IsSendAddressToOpportunity__c.field-meta.xml
<CustomField>
    <fullName>IsSendAddressToOpportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Address to Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QuoteDiscount__c.field-meta.xml
<CustomField>
    <fullName>QuoteDiscount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quote Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TechnicianId__c.field-meta.xml
<CustomField>
    <fullName>TechnicianId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/LineCost__c.field-meta.xml
<CustomField>
    <fullName>LineCost__c</fullName>
    <label>Line Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/QuoteLineSubItem__c.object-meta.xml
<CustomObject>
    <label>Quote Line Sub Item</label>
    <nameField>
        <label>Quote Line Sub Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Sub Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLineSubItem__c/fields/QuoteLineItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItemId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Quote Line Sub Items</relationshipLabel>
    <relationshipName>QuoteLineSubItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestForTechnician__c/RequestForTechnician__c.object-meta.xml
<CustomObject>
    <label>Request For Technician</label>
    <nameField>
        <displayFormat>RFT-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request For Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestForTechnician__c/fields/DescriptionForTechnician__c.field-meta.xml
<CustomField>
    <fullName>DescriptionForTechnician__c</fullName>
    <label>Description For Technician</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RequestForTechnician__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Name</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Request For Technicians</relationshipLabel>
    <relationshipName>RequestForTechnicians</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestForTechnician__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RequestStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestForTechnician__c/fields/TechnicianId__c.field-meta.xml
<CustomField>
    <fullName>TechnicianId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technician</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RequestForTechnicians</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SyncServiceSettings__c/SyncServiceSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SyncServiceSettings</label>
</CustomObject>

force-app/main/default/objects/SyncServiceSettings__c/fields/DisableSync__c.field-meta.xml
<CustomField>
    <fullName>DisableSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <description>Must be set manually by administrator</description>
    <externalId>true</externalId>
    <inlineHelpText>Must be set manually by administrator</inlineHelpText>
    <label>SAP ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Contact_Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Dealer</fullName>
    </customValue>
    <customValue>
        <fullName>End user</fullName>
    </customValue>
    <masterLabel>Contact Role</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/RequestStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Requested</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <description>Request For Technician</description>
    <masterLabel>Request Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TriggerTest.cls
@isTest 
private class TriggerTest {

    @isTest
    private static void triggerTestMethod() {
        SyncServiceSettings__c[] stts = new SyncServiceSettings__c[]{};
        stts.add(new SyncServiceSettings__c(Name = 'AccountToSAP', DisableSync__c = true));
        stts.add(new SyncServiceSettings__c(Name = 'OrderToSAP', DisableSync__c = true));
        stts.add(new SyncServiceSettings__c(Name = 'ProductToSAP', DisableSync__c = false));
        insert stts;

        Profile[] prof = [SELECT Id FROM Profile];
        User u = new User(LastName = 'test', ProfileId = prof[0].Id, Username='test@silentlab.cz', EmailEncodingKey = 'UTF-8', Email='test@test.cz', Alias='test', CommunityNickname='test', TimeZoneSidKey='Europe/Berlin', LocaleSidKey='en_US', LanguageLocaleKey='en_US');
        insert u;
        Product2 prod = new Product2(Name='MICRO OFFICE',IsActive=true,ProductCode='ABCD',SAPId__c='A0123',UnitPriceCZK__c=1000,UnitPriceEUR__c=20);
        insert prod;
        Product2 subProd = new Product2(Name='Cloth for MO',IsActive=true,ProductCode='CFMO',SAPId__c='A0456');
        insert subProd;
        BOM__c bom = new BOM__c(BundleId__c=prod.Id,BundleItemId__c=subProd.Id,Quantity__c=10);
        insert bom;

        Id pricebookId = Test.getStandardPricebookId();
        String currForTest = Cst.CURR_CZK;

        // Update product price for EUR
        prod.UnitPriceEUR__c = 15;
        update prod;

        PricebookEntry pbe = [SELECT Id FROM PricebookEntry WHERE Product2Id=:prod.Id AND CurrencyIsoCode=:currForTest LIMIT 1];
        
        Opportunity opp = new Opportunity(StageName='Qualification', Name='Opp Test', CloseDate=Date.newInstance(2019, 8, 24), Realisation_Start_confirmed__c = true);
        insert opp;
        Quote qt = new Quote(Name='Quote Test', OpportunityId=opp.Id, Pricebook2Id = pricebookId, QuoteDiscount__c = 0);
        insert qt;
        Order__c ord = new Order__c(Name = 'Order Test', OpportunityId__c = opp.Id, QuoteId__c = qt.Id, ShippingAddressTxt__c = 'xxx', RealizationStartDate__c = Date.today(), RealizationEndDate__c = Date.today().addDays(2));
        insert ord;
        Invoice__c inv = new Invoice__c(Name = 'Invoice Test', OrderId__c = ord.Id);
        Insert inv;
        RequestForTechnician__c rft = new RequestForTechnician__c(DescriptionForTechnician__c = 'Test', QuoteId__c = qt.Id, Status__c='Done', CurrencyIsoCode=opp.CurrencyIsoCode);
        insert rft;
        rft.TechnicianId__c = u.Id;
        update rft;
        Product2 prod2 = new Product2(Name='MICRO OFFICE',IsActive=true,ProductCode='ABCD',SAPId__c='A0123',UnitPriceCZK__c=1000,UnitPriceEUR__c=20, RequestForTechnicianId__c = rft.Id);
        insert prod2;
        rft.Status__c = Cst.RFT_STATUS_DONE;
        update rft;

        QuoteLineItem qli = new QuoteLineItem(QuoteId=qt.Id, Quantity=10, UnitPrice=10, Product2Id=prod.Id, PricebookEntryId = pbe.Id, LineCost__c = 10);
        insert qli;
        QuoteLineSubItem__c qlsi = new QuoteLineSubItem__c(QuoteLineItemId__c=qli.Id);
        insert qlsi;

        Account a = new Account(Name='Test', VatNo__c = '1231244324', IsValidated__c=true,BillingCity='Praha');
        insert a;

        Contact c = new Contact(LastName='Lname', AccountId = a.Id, Role__c='End user');
        insert c;

        opp.StageName = 'Closed Won';
        opp.Street__c = 'street';
        opp.City__c = 'City';
        opp.PostalCode__c = '12345';
        opp.Country__c = 'Czech republic';
        opp.AccountId = a.Id;
        opp.OrderDueDate__c = System.today();
        opp.RealizationStartDate__c = System.today();
        opp.RealizationEndDate__c = System.today();
        opp.PrimaryContact__c = c.id;
        opp.SyncedQuoteId = qt.Id;

        update opp;
    }

    @IsTest
    private static void should_UpdateOpportunityAddressFields_when_UpdateQuoteAddressFieldsAreDifferentAndSyncAddressIsOn() {
        Id pricebookId = Test.getStandardPricebookId();

        Opportunity testOpportunity = new Opportunity(
                StageName='Qualification',
                Name='Opp Test',
                CloseDate = Datetime.now().addDays(30).date(),
                Realisation_Start_confirmed__c = true,
                Country__c = 'Poland',
                Street__c = 'Test2023'
            );

        insert testOpportunity;

        Quote testQuote = new Quote(
                Name='Quote Test',
                OpportunityId = testOpportunity.Id,
                Pricebook2Id = pricebookId,
                QuoteDiscount__c = 0,
                IsSendAddressToOpportunity__c = false,
                ShippingStreet = 'TestQuote',
                ShippingCity = 'TestCity',
                ShippingState = 'New York',
                ShippingPostalCode = '10022',
                ShippingCountry = 'United States'
            );

        insert testQuote;

        testOpportunity.SyncedQuoteId = testQuote.Id;

        update testOpportunity;

        Test.startTest();

        testQuote.IsSendAddressToOpportunity__c = true;
        update testQuote;

        Test.stopTest();

        Opportunity updatedOpportunity = [SELECT Id, Street__c, City__c, State__c, PostalCode__c, Country__c FROM Opportunity WHERE Name = 'Opp Test' LIMIT 1];

        Assert.areEqual('TestQuote', updatedOpportunity.Street__c, 'Street on opportunity should be updated with value from Quote!');
        Assert.areEqual('TestCity', updatedOpportunity.City__c, 'City on opportunity should be updated with value from Quote!');
        Assert.areEqual('New York', updatedOpportunity.State__c, 'State on opportunity should be updated with value from Quote!');
        Assert.areEqual('10022', updatedOpportunity.PostalCode__c, 'PostalCode on opportunity should be updated with value from Quote!');
        Assert.areEqual('United States', updatedOpportunity.Country__c, 'Country on opportunity should be updated with value from Quote!');
    }
}