force-app/main/default/objects/Account/fields/VatNo__c.field-meta.xml
<CustomField>
    <fullName>VatNo__c</fullName>
    <inlineHelpText>IČ</inlineHelpText>
    <label>IČ</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contact_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OrderDeliveryDatePlan__c.field-meta.xml
<CustomField>
    <fullName>OrderDeliveryDatePlan__c</fullName>
    <inlineHelpText>= Realization End</inlineHelpText>
    <label>Order Delivery Date Plan</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProformaIssuedDatePlan__c.field-meta.xml
<CustomField>
    <fullName>ProformaIssuedDatePlan__c</fullName>
    <label>Proforma Issued Date Plan</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProformaPaidDatePlan__c.field-meta.xml
<CustomField>
    <fullName>ProformaPaidDatePlan__c</fullName>
    <label>Proforma Paid Date Plan</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SyncServiceSettings__c/SyncServiceSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SyncServiceSettings</label>
</CustomObject>

force-app/main/default/objects/SyncServiceSettings__c/fields/DisableSync__c.field-meta.xml
<CustomField>
    <fullName>DisableSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SyncServiceSettings__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Stores API Name of Named Credential with appended path to the endpoint for the service.</description>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Contact_Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Dealer</fullName>
    </customValue>
    <customValue>
        <fullName>End user</fullName>
    </customValue>
    <masterLabel>Contact Role</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
/*
 Author: Dominik Cwynar (dominikcwynar@nextviewconsulting.com)
 Description: Class containing methods to create records for tests 
 */
@IsTest
global class TestDataFactory {
  public static List<SyncServiceSettings__c> createSyncServiceSettings(
    Boolean doInsert
  ) {
    SyncServiceSettings__c[] settings = new List<SyncServiceSettings__c>{};
    List<String> serviceNames = new List<String>{
      'AccountToSAP',
      'ContactsToSAP',
      'OrderToSAP',
      'ProductToSAP',
      'ProductToSF',
      'OrderToSF',
      'AccountToSF',
      'InvoiceToSF',
      'PaymentToSF'
    };

    for (String service : serviceNames) {
      settings.add(
        new SyncServiceSettings__c(
          Name = service,
          DisableSync__c = false,
          Endpoint__c = 'TestNamedCredential/test',
          Token__c = 'testToken'
        )
      );
    }

    if (doInsert) {
      insert settings;
    }

    return settings;
  }

  public static Account createAccount(Boolean doInsert) {
    Account account = new Account(
      Name = 'TestACC' + DateTime.now(),
      VatNo__c = '123456780',
      BillingCity = 'Praha'
    );

    if (doInsert) {
      insert account;
    }

    return account;
  }

  public static Contact createContact(Id accountId, Boolean doInsert) {
    if (accountId == null) {
      accountId = createAccount(true).Id;
    }

    Contact contact = new Contact(
      AccountId = accountId,
      LastName = 'TestCON' + DateTime.now().millisecond(),
      Role__c = 'End user',
      Email = 'example' + DateTime.now().millisecond() + '@example.com',
      Phone = String.valueOf(DateTime.now().millisecond())
    );

    if (doInsert) {
      insert contact;
    }

    return contact;
  }

  public static Opportunity createOpportunity(
    Id accountId,
    Boolean doInsert,
    String stageName
  ) {
    if (accountId == null) {
      accountId = createAccount(true).Id;
    }
    Opportunity oppty = new Opportunity(
      Name = 'TestACC' + DateTime.now(),
      AccountId = accountId,
      CloseDate = DateTime.now().addDays(5).date(),
      StageName = !String.isBlank(stageName)
        ? stageName
        : Cst.OPPORTUNITY_STAGE_FINALIZING,
      Street__c = 'AnyStreet 123',
      City__c = 'Prague',
      PostalCode__c = '12345',
      Country__c = 'Czech Republic',
      CurrencyIsoCode = 'EUR',
      ProformaIssuedDatePlan__c = Date.today().addMonths(2),
      ProformaPaidDatePlan__c = Date.today().addMonths(2),
      OrderDeliveryDatePlan__c = Date.today().addMonths(2)
    );

    if (doInsert) {
      insert oppty;
    }
    return oppty;
  }

  public static Product2 createProduct2(Boolean doInsert) {
    Product2 product = new Product2(Name = 'MICRO OFFICE', IsActive = true);

    if (doInsert) {
      insert product;
    }

    return product;
  }
}