force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/TotalWithVAT__c.field-meta.xml
<CustomField>
    <fullName>TotalWithVAT__c</fullName>
    <label>Total with VAT</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoicePaymentCalculationTest.cls
@IsTest
public with sharing class InvoicePaymentCalculationTest {
	@IsTest
	public static void InvoicePaymentCalculationTest() {
		Invoice__c inv = new Invoice__c(TotalWithVAT__c = 1000, CurrencyIsoCode = 'CZK');
		insert inv;

		Payment__c p = new Payment__c(Amount__c = 1000, CurrencyIsoCode = 'CZK', InvoiceId__c = inv.Id);
		insert p;
		InvoicePaymentCalculationSchedulable.scheduleJob();
		InvoicePaymentCalculationSchedulable.cancel();

		Test.startTest();
		InvoicePaymentCalculationSchedulable.worker();
		Test.stopTest();
	}
}