force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/IsPaid__c.field-meta.xml
<CustomField>
    <fullName>IsPaid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/TotalWithVAT__c.field-meta.xml
<CustomField>
    <fullName>TotalWithVAT__c</fullName>
    <label>Total with VAT</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoicePaymentCalculation.cls
public with sharing class InvoicePaymentCalculation {
	@InvocableMethod
	public static void InvoicePaymentCalculation(Id[] invIds) {
		System.debug(invIds);
		Database.executeBatch(new InvoicePaymentCalculationBatch(invIds), 1);
		
		/*Invoice__c[] invToRecalc = [SELECT Id, IsPaid__c, PaidDate__c, CurrencyIsoCode, TotalWithVAT__c, (SELECT Id, Amount__c, CurrencyIsoCode FROM Payments__r)
								FROM Invoice__c 
								WHERE Id IN: invIds];

		Invoice__c[] invToUpdate = new Invoice__c[]{};
		for(Invoice__c inv : invToRecalc){
			// calc sum of related payments (only in same currency as invoice)
			Decimal paymentsSum = 0;
			for(Payment__c p : inv.Payments__r){
				if(inv.CurrencyIsoCode == p.CurrencyIsoCode){
					paymentsSum += p.Amount__c;
				}
			}

			// check if should be marked as paid
			if(paymentsSum == inv.TotalWithVAT__c){
				inv.IsPaid__c = true;
				inv.PaidDate__c = System.today();
				invToUpdate.add(inv);
			}
		}

		if(!invToUpdate.isEmpty()){
			update invToUpdate;
		}*/
	}
}