force-app/main/default/objects/SyncServiceSettings__c/SyncServiceSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SyncServiceSettings</label>
</CustomObject>

force-app/main/default/objects/SyncServiceSettings__c/fields/DisableSync__c.field-meta.xml
<CustomField>
    <fullName>DisableSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QActionPDFPreviewControllerTest.cls
@isTest 
private class QActionPDFPreviewControllerTest {

	@isTest
	private static void auraSavePDFTest() {
		SyncServiceSettings__c stt = new SyncServiceSettings__c();
		stt.Name = 'AccountToSAP';
		stt.DisableSync__c = true;
		insert stt;

		Opportunity opp = new Opportunity(StageName='Qualification', Name='Opp Test', CloseDate=Date.newInstance(2019, 8, 24));	
		insert opp;
		Quote qt = new Quote(Name='Quote Test', OpportunityId=opp.Id);
		insert qt;

		QActionPDFPreviewController.auraSavePDF(qt.Id, 'QuotePDF');
	}
}