force-app/main/default/objects/BOM__c/BOM__c.object-meta.xml
<CustomObject>
    <description>Bill Of Material</description>
    <label>BOM</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BOM__c/fields/BundleId__c.field-meta.xml
<CustomField>
    <fullName>BundleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to bundle master product.</description>
    <inlineHelpText>Relation to bundle master product.</inlineHelpText>
    <label>Bundle</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Items (list of material)</relationshipLabel>
    <relationshipName>BOMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/RequestForTechnicianId__c.field-meta.xml
<CustomField>
    <fullName>RequestForTechnicianId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request For Technician</label>
    <referenceTo>RequestForTechnician__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductDescription__c/ProductDescription__c.object-meta.xml
<CustomObject>
    <label>Product Description</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDescription__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Descriptions</relationshipLabel>
    <relationshipName>ProductDescriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RFTProductListController.cls
public without sharing class RFTProductListController  {

	@AuraEnabled
	public static String auraGetProds(String recordId){
		Mdl.RFTMdlList[] rftmdlS = new Mdl.RFTMdlList[]{};
		Product2[] prods = [SELECT Id, Name FROM Product2 WHERE RequestForTechnicianId__c =: recordId];
		for(Product2 prod : prods){
			Mdl.RFTMdlList rftmdl = new Mdl.RFTMdlList();
			rftmdl.id = prod.Id;
			rftmdl.name = prod.Name;
			rftmdlS.add(rftmdl);
		}
		System.debug('RFTMDL' + rftmdlS);
		return JSON.serialize(rftmdlS);

	}

	@AuraEnabled
	public static String auraDeleteProduct(String prodId, String recordId){
		BOM__c[] boms = [SELECT Id FROM BOM__c WHERE BundleId__c =: prodId];
		delete boms;
		ProductDescription__c[] prodDescs = [SELECT Id FROM ProductDescription__c WHERE ProductId__c =: prodId];
		delete prodDescs;

		ContentDocumentLink[] cdls = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: prodId];
		ContentDocument[] cds = new ContentDocument[]{};
		for(ContentDocumentLink cdl : cdls){
			ContentDocument cd = new ContentDocument(Id = cdl.ContentDocumentId);
			cds.add(cd);
		}
		delete cds;
		
		Product2[] prods = [SELECT Id FROM Product2 WHERE Id =: prodId];
		delete prods;
		return auraGetProds(recordId);
	}
}