force-app/main/default/objects/BOM__c/BOM__c.object-meta.xml
<CustomObject>
    <description>Bill Of Material</description>
    <label>BOM</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BOM__c/fields/IsVisible__c.field-meta.xml
<CustomField>
    <fullName>IsVisible__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if it is visible in the Quote Manager</description>
    <inlineHelpText>Determines if it is visible in the Quote Manager</inlineHelpText>
    <label>Visible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/IsVisibleOnPDF__c.field-meta.xml
<CustomField>
    <fullName>IsVisibleOnPDF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visibel On PDF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantity in Bundle.</description>
    <inlineHelpText>Quantity in Bundle.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/SortNumber__c.field-meta.xml
<CustomField>
    <fullName>SortNumber__c</fullName>
    <formula>/*CASE( Type__c, 
 		&apos;Látka&apos;, 1, 
 		&apos;Látka sezení&apos;, 2, 
 		&apos;Látka polštáře&apos;, 3, 
 		&apos;Počet modulů&apos;, 4, 
 		&apos;Prosklený strop&apos;, 5, 
 		&apos;Rám&apos;, 6, 
 		&apos;Madlo&apos;, 7,
 		&apos;Panty&apos;, 8,
 		&apos;Výška stolu&apos;, 9,
 		&apos;Zásuvka&apos;, 10,
 		&apos;Vybavení&apos;, 11,
 		&apos;Doprava&apos;, 12,
 		&apos;Montáž&apos;, 13,
 		&apos;Balení&apos;, 14,
 		15)
*/
1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sort Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Specification__c.field-meta.xml
<CustomField>
    <fullName>Specification__c</fullName>
    <formula>IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;1&quot;),&quot;SPRINKLER&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;2&quot;),&quot;Madlo&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;3&quot;),&quot;Panty&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;4&quot;),&quot;Dveřní těsnění&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;5&quot;),&quot;Zasklívací těsnění&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;6&quot;),&quot;Stolek PRIME&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;7&quot;),&quot;Zdrojový kabel&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;8&quot;),&quot;Zásuvka v panelu - PRIME,UNIQ&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;9&quot;),&quot;Zásuvkový panel 4-modulový volně stojící / na stolku&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;10&quot;),&quot;Čalounění&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;11&quot;),&quot;Výroba&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;12&quot;),&quot;SOFT&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;13&quot;),&quot;AMBIENT&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;14&quot;),&quot;PULSE&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;15&quot;),&quot;Umístění stolku UNIQ&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;16&quot;),&quot;16&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;17&quot;),&quot;17&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;18&quot;),&quot;18&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;19&quot;),&quot;Rám - PRIME&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;20&quot;),&quot;Rám - UNIQ&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;21&quot;),&quot;Rám - CUBIQ&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;22&quot;),&quot;Rám - QI&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;23&quot;),&quot;Rám - QUADRIO&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;24&quot;),&quot;Strop QUADRIO&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;25&quot;),&quot;Umístění stolku PRIME&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;26&quot;),&quot;Zásuvka v panelu - CUBIQ,QI&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;27&quot;),&quot;Zásuvka v panelu QII-QIV&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;28&quot;),&quot;Látka na akustické závěsy&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;29&quot;),&quot;Zásuvka v panelu - SPARK, UNIQ&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;30&quot;),&quot;30&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;31&quot;),&quot;Rám - SPARK&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;32&quot;),&quot;32&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;33&quot;),&quot;Externí opláštění - SPARK&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;34&quot;),&quot;Externí opláštění - SPARK²&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;35&quot;),&quot;Externí opláštění - SPARK⁴&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;36&quot;),&quot;Rám SPARK²/ ⁴&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;37&quot;),&quot;Zásuvka pod stolem / na zemi - SPARK²&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;38&quot;),&quot;Zásuvka ve stolku - SPARK⁴&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;39&quot;),&quot;Zásuvka na zemi- SPARK⁴&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;40&quot;),&quot;Látka interiérových obkladů&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;41&quot;),&quot;Zásuvka ve stolku - SPARK²&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;42&quot;),&quot;Látka sezení SPARK&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;43&quot;),&quot;Příplatek Extra&quot;,NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Specification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(BundleItemId__r.Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityNo__c.field-meta.xml
<CustomField>
    <fullName>OpportunityNo__c</fullName>
    <label>Opportunity No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BusinessName__c.field-meta.xml
<CustomField>
    <fullName>BusinessName__c</fullName>
    <label>Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BusinessNameEN__c.field-meta.xml
<CustomField>
    <fullName>BusinessNameEN__c</fullName>
    <label>Business Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductDescriptionCZ__c.field-meta.xml
<CustomField>
    <fullName>ProductDescriptionCZ__c</fullName>
    <label>Product Description CZ</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductDescriptionEN__c.field-meta.xml
<CustomField>
    <fullName>ProductDescriptionEN__c</fullName>
    <label>Product Description EN</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Specification__c.field-meta.xml
<CustomField>
    <fullName>Specification__c</fullName>
    <label>Specification</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductSpecification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M-AKU_PENA</fullName>
            </value>
            <value>
                <fullName>M-BARVY</fullName>
            </value>
            <value>
                <fullName>M-DROBNY_SPMAT</fullName>
            </value>
            <value>
                <fullName>M-ELEKTRO</fullName>
            </value>
            <value>
                <fullName>M-FUKUMA</fullName>
            </value>
            <value>
                <fullName>M-KOV</fullName>
            </value>
            <value>
                <fullName>M-KOVANI</fullName>
            </value>
            <value>
                <fullName>M-LATKA</fullName>
            </value>
            <value>
                <fullName>M-MICROOFFICE</fullName>
            </value>
            <value>
                <fullName>M-OBALY</fullName>
            </value>
            <value>
                <fullName>M-OSTATNI</fullName>
            </value>
            <value>
                <fullName>M-PLOSNY_MAT</fullName>
            </value>
            <value>
                <fullName>M-SKLO</fullName>
            </value>
            <value>
                <fullName>P-POLOTOVAR</fullName>
            </value>
            <value>
                <fullName>S-SKLADOVE SLUZBY</fullName>
            </value>
            <value>
                <fullName>S-SLUZBY</fullName>
            </value>
            <value>
                <fullName>V-VYROBEK</fullName>
            </value>
            <value>
                <fullName>Z-ZBOZI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>en_US</fullName>
                <label>EN</label>
            </value>
            <value>
                <fullName>cs</fullName>
                <label>CS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProductFamily__c.field-meta.xml
<CustomField>
    <fullName>ProductFamily__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RelatedOptionalEquipment__c.field-meta.xml
<CustomField>
    <fullName>RelatedOptionalEquipment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Optional Equipment</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Quote Line Items (Related Optional Equipment)</relationshipLabel>
    <relationshipName>QuoteLineItem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RowDiscount__c.field-meta.xml
<CustomField>
    <fullName>RowDiscount__c</fullName>
    <label>Row Discount</label>
    <precision>15</precision>
    <scale>12</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/QuoteLineSubItem__c.object-meta.xml
<CustomObject>
    <label>Quote Line Sub Item</label>
    <nameField>
        <label>Quote Line Sub Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Sub Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLineSubItem__c/fields/IsVisible__c.field-meta.xml
<CustomField>
    <fullName>IsVisible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/fields/IsVisibleOnPDF__c.field-meta.xml
<CustomField>
    <fullName>IsVisibleOnPDF__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visibel On PDF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/fields/Product2Id__c.field-meta.xml
<CustomField>
    <fullName>Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Sub Items</relationshipLabel>
    <relationshipName>Quote_Line_Sub_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/fields/ProductDescriptionCZ__c.field-meta.xml
<CustomField>
    <fullName>ProductDescriptionCZ__c</fullName>
    <label>Product Description CZ</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/fields/ProductDescriptionEN__c.field-meta.xml
<CustomField>
    <fullName>ProductDescriptionEN__c</fullName>
    <label>Product Description EN</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/fields/QuoteLineItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItemId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Quote Line Sub Items</relationshipLabel>
    <relationshipName>QuoteLineSubItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SpecificationPdfController.cls
public class SpecificationPdfController  {

	private final Quote quote;
	public QuoteLineItem[] 			qlis			{get;set;}
	public String 					currentDate 	{get;set;}
	public ContentDocumentLink[]	prodImg			{get;set;}
	public ContentDocumentLink[]	prodLay			{get;set;}
	//public BOM__c[]					boms			{get;set;}
	public Mdl.SpecificationMdl[]	sms 			{get;set;}
	public QuoteLineItem[] 			qlisOpt 		{get;set;}

	// Number formating settings
    private final Integer precision = 2;
	private final String separator = ' ';
	private final String decimalSeparator = ',';

	public SpecificationPdfController(ApexPages.StandardController stdc){
		prodImg = new ContentDocumentLink[]{};
		prodLay = new ContentDocumentLink[]{};
		sms = new Mdl.SpecificationMdl[]{};
		qlisOpt = new QuoteLineItem[]{};
		Id[] prodIds = new Id[]{};

		String[] fieldsToAdd = new String[]{'Id', 'QuoteNumber', 'Name', 'Language__c',
											'Opportunity.Name', 'Opportunity.OpportunityNo__c'};

		if(!Test.isRunningTest()){
			stdc.addFields(fieldsToAdd);
		}

		this.quote = (Quote)stdc.getRecord();

		QuoteLineItem[] qlis = [SELECT Discount, Subtotal, RowDiscount__c, TotalPrice, ProductDescriptionCZ__c, ProductDescriptionEN__c, UnitPrice, Quantity, ProductFamily__c, 
								ProductName__c, CurrencyIsoCode, Description, Product2Id, Product2.BusinessName__c, Product2.BusinessNameEN__c, RelatedOptionalEquipment__c, Product2.Type__c, Product2.Name,
								(SELECT Id, Name, ProductName__c, Description__c, ProductDescriptionCZ__c, ProductDescriptionEN__c, Quantity__c, Product2Id__r.BusinessName__c, Product2Id__r.BusinessNameEN__c, 
								Product2Id__r.Name, Product2Id__r.Specification__c, Product2Id__r.Type__c
									FROM QuoteLineSubItems__r WHERE IsVisible__c = true AND IsVisibleOnPDF__c = true ORDER BY SortNumber__c)
								FROM QuoteLineItem WHERE QuoteId =: quote.Id AND IsTransport__c = false ORDER BY RowNumber__c ASC];
		

		for(QuoteLineItem qli : qlis){
			prodIds.add(qli.Product2Id);
			System.debug('QLI ' + qli.RelatedOptionalEquipment__c);
			if(!String.isBlank(qli.RelatedOptionalEquipment__c)){
				qlisOpt.add(qli);
			}
		}
		System.debug('QLIOpt ' + qlisOpt);
		
		/*BOM__c[] boms = [SELECT Type__c, BundleItemId__r.Name, BundleId__c, Quantity__c FROM BOM__c WHERE BundleId__c IN: prodIds AND IsVisible__c = true ORDER BY SortNumber__c];
		System.debug('BOMS ' + boms);*/


		for(QuoteLineItem qli : qlis){
			if(qli.Product2.Type__c == Cst.PROD_TYPE_PRODUCT){
				Mdl.SpecificationMdl sm = new Mdl.SpecificationMdl();
				sm.qli = qli;
				for(QuoteLineSubItem__c qlsi: qli.QuoteLineSubItems__r){
					sm.qlsis.add(qlsi);
				}
				for(QuoteLineItem optQli : qlis){
					if(optQli.RelatedOptionalEquipment__c == qli.Id){
						sm.optQlis.add(optQli);
					}
				}
				sms.add(sm);
			}
		}	
		Datetime currDateTime = datetime.now();
		currentDate = currDateTime.format('dd.MM.YYYY');

		if(prodIds.size() > 0){
			
			for(ContentDocumentLink cdl: [SELECT ContentDocument.LatestPublishedVersionId, LinkedEntityId, ContentDocument.Title FROM ContentDocumentLink WHERE LinkedEntityId IN: prodIds]){
				if(cdl.ContentDocument.Title == 'Specification'){
					this.prodImg.add(cdl);
				}else if(cdl.ContentDocument.Title == 'SpecificationDetail' && quote.Language__c == 'cs'){
					this.prodLay.add(cdl);
				}else if(cdl.ContentDocument.Title == 'SpecificationDetailEN' && quote.Language__c == 'en_US'){
					this.prodLay.add(cdl);
				}
			}
		}
	}
}