force-app/main/default/objects/BOM__c/BOM__c.object-meta.xml
<CustomObject>
    <description>Bill Of Material</description>
    <label>BOM</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BOM__c/fields/BundleId__c.field-meta.xml
<CustomField>
    <fullName>BundleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to bundle master product.</description>
    <inlineHelpText>Relation to bundle master product.</inlineHelpText>
    <label>Bundle</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Items (list of material)</relationshipLabel>
    <relationshipName>BOMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/BundleItemSAPId__c.field-meta.xml
<CustomField>
    <fullName>BundleItemSAPId__c</fullName>
    <description>Kód artiklu ze SAP - dílec (materiál)</description>
    <inlineHelpText>Kód artiklu ze SAP - dílec (materiál)</inlineHelpText>
    <label>Bundle Item SAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/BundleSAPId__c.field-meta.xml
<CustomField>
    <fullName>BundleSAPId__c</fullName>
    <description>Kód Artiklu v SAP (nadřazený výrobek)</description>
    <inlineHelpText>Kód Artiklu v SAP (nadřazený výrobek)</inlineHelpText>
    <label>Bundle SAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/EId__c.field-meta.xml
<CustomField>
    <fullName>EId__c</fullName>
    <description>&lt;Bundle SAP ID&gt;-&lt;Bundle Item SAP ID&gt;&lt;Row Number&gt;</description>
    <formula>BundleId__r.SAPId__c + &quot;-&quot; + BundleItemId__r.SAPId__c + &quot;-&quot; + TEXT(RowNumber__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>&lt;Bundle SAP ID&gt;-&lt;Bundle Item SAP ID&gt;&lt;Row Number&gt;</inlineHelpText>
    <label>External ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position from SAP</description>
    <inlineHelpText>Position from SAP</inlineHelpText>
    <label>Position</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/RowNumber__c.field-meta.xml
<CustomField>
    <fullName>RowNumber__c</fullName>
    <label>Row Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <label>SAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <externalId>true</externalId>
    <label>SAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SyncServiceSettings__c/SyncServiceSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SyncServiceSettings</label>
</CustomObject>

force-app/main/default/objects/SyncServiceSettings__c/fields/DisableSync__c.field-meta.xml
<CustomField>
    <fullName>DisableSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SyncServiceSettings__c/fields/ForceStatusCode__c.field-meta.xml
<CustomField>
    <fullName>ForceStatusCode__c</fullName>
    <description>Used for Response Status Code manual setup - it has no consequence wit the service run - it will always end with this status (direction TO SF ONLY)</description>
    <inlineHelpText>Used for Response Status Code manual setup - it has no consequence wit the service run - it will always end with this status (direction TO SF ONLY)</inlineHelpText>
    <label>Force Status Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Svc_ProductToSF.cls
@RestResource(urlMapping='/sync/product')
global without sharing class Svc_ProductToSF  {
    private static String SVC_NAME = 'ProductToSF';
    private static SyncServiceSettings__c stt = SyncServiceSettings__c.getValues(SVC_NAME);
    // https://<org-domain>/services/apexrest/sync/product

	@HttpPost
    global static void doPost() {
        if(stt.DisableSync__c){ SyncUtils.logServiceActivity(SVC_NAME, Cst.STATUS_ERROR, 503, 'ERROR: Service is disabled'); return; }

	    // Get valid settings
	    String validToken = 'Baerer '+stt.Token__c;
	    // Also for testing
	    if(Test.isRunningTest()){ validToken = 'Baerer '+'XXXXX'; }

	    RestRequest req = RestContext.request;
	    RestResponse res = RestContext.response;

	    String token = req.headers.get('token');
        String body = (req.requestBody != null) ? req.requestBody.toString() : '';
        System.debug('body: '+body);

        // Validate token
        if(String.isEmpty(token) || token != validToken){
            res.statusCode = 401;
            res.responseBody = Blob.valueOf('Invalid token - requested ('+token+')');
            return;
        }

        // Insert inbound records - lsit of Products
        String msg = 'SUSCCESS: Products synced.';
		String stackTrace;
		String status = Cst.STATUS_SUCCESS;
		String errStr = '';
        res.statusCode = 200;
        try{
			Mdl.SfProduct[] recsFromJson = (Mdl.SfProduct[])JSON.deserialize(SyncUtils.getValidJsonForCustomModel(body), Mdl.SfProduct[].class);

			// Get Existing records
			Set<String> exProdSAPIds = new Set<String>();
			Set<String> exBOMEIds = new Set<String>();
			Mdl.SfProduct[] recs = new Mdl.SfProduct[]{};
			for(Mdl.SfProduct r : recsFromJson){
				if(exProdSAPIds.contains(r.SAPId)){ continue; } // Skip duplicates
				exProdSAPIds.add(r.SAPId);
				recs.add(r);
				Mdl.SfBom[] sfBoms = (r.BOMs != null && r.BOMs.Records != null) ? r.BOMs.Records : new Mdl.SfBom[]{};
				for(Mdl.SfBom b : sfBoms){
					exProdSAPIds.add(b.BundleSAPId);
					exBOMEIds.add(r.SAPId+'-'+b.BundleItemSAPId+'-'+b.RowNumber);
				}
			}
			
			
			System.debug('exBOMEIds:'+exBOMEIds);
			
			BOM__c[] exBOMs = [SELECT Id,SAPId__c,EId__c, BundleSAPId__c, BundleItemSAPId__c, Position__c, RowNumber__c FROM BOM__c WHERE EId__c IN:exBOMEIds];
			Map<String,Id> exBOMsByEId = new Map<String,Id>(); // <BOM EId__c, SF ID>
			for(BOM__c b : exBOMs){
				exBOMsByEId.put(b.EId__c, b.Id);
			}

			Product2[] prodsToUpsert = new Product2[]{};
			// Upsert products to obtain SF ids
			for(Mdl.SfProduct r : recs){
				Product2 p = SyncUtils.mapProductFields(r);
				prodsToUpsert.add(p);
			}
			// UPSERT PRODUCTS
			Database.UpsertResult[] purs = Database.upsert(prodsToUpsert, Product2.SAPId__c.getDescribe().getSObjectField(), false);
            for(Integer i=0; i<purs.size();i++){
                if(!purs[i].isSuccess()){
                    errStr += 'ERROR: '+purs[i].getErrors()+'\n\n'+'UPSERTED PRODUCT: '+JSON.serializePretty(recs[i]+'\n\n');
                }
            }

			// Get also SF ids for currently inserted products
			Product2[] exProds = [SELECT Id,SAPId__c,(SELECT Id,SAPId__c,EId__c, BundleSAPId__c, BundleItemSAPId__c, Position__c, RowNumber__c FROM BOMs__r) FROM Product2 WHERE SAPId__c IN:exProdSAPIds];
			Map<String,Product2> exProdsBySAPId = new Map<String,Product2>(); // <Product SAPId__c, Product2>
			for(Product2 p : exProds){
				exProdsBySAPId.put(p.SAPId__c, p);
			}

			// Assign proper values
			BOM__c[] bomsToUpsert = new BOM__c[]{};
			BOM__c[] bomsToDelete = new BOM__c[]{};
			for(Integer i=0; i<prodsToUpsert.size(); i++){

				Product2 p = prodsToUpsert[i];
				Mdl.SfProduct r = recs[i];

				Map<String,BOM__c> bomsToDelMap = new Map<String,BOM__c>();
				Product2 tmpProd = exProdsBySAPId.get(r.SAPId);
				if(tmpProd != null && tmpProd.BOMs__r != null){
					for(BOM__c b : exProdsBySAPId.get(r.SAPId).BOMs__r){
						bomsToDelMap.put(b.EId__c,b);
					}
				}
				
				Mdl.SfBom[] sfBoms = (r.BOMs != null && r.BOMs.Records != null) ? r.BOMs.Records : new Mdl.SfBom[]{};
				for(Mdl.SfBom b : sfBoms){
					String bEId = r.SAPId+'-'+b.BundleItemSAPId+'-'+b.RowNumber;
					b.Id = exBOMsByEId.get(bEId);
					b.BundleId = p.Id;
					b.BundleItemId = exProdsBySAPId.get(b.BundleItemSAPId).Id; // Product (Material) must exist - it's logical premise, because it must be created in SAP and already synced to SF
					bomsToUpsert.add(SyncUtils.mapBomFields(b));
					bomsToDelMap.remove(bEId);
				}
				bomsToDelete.addAll(bomsToDelMap.values());
			}

			
			// UPSERT BOMs
			Database.UpsertResult[] burs = Database.upsert(bomsToUpsert, BOM__c.Id.getDescribe().getSObjectField(), false);
			for(Integer i=0; i<burs.size();i++){
				if(!burs[i].isSuccess()){
					errStr += 'ERROR: '+burs[i].getErrors()+'\n\n'+'UPSERTED BOM: '+JSON.serializePretty(bomsToUpsert[i]+'\n\n');
				}
			}
			// DELETE BOMs
			Database.DeleteResult[] bdrs = Database.delete(bomsToDelete, false);
			for(Integer i=0; i<bdrs.size();i++){
				if(!bdrs[i].isSuccess()){
					errStr += 'ERROR: '+bdrs[i].getErrors()+'\n\n'+'DELETED BOM: '+JSON.serializePretty(bomsToDelete[i]+'\n\n');
				}
			}
			// LOG SAVE RESULT PROBLEMS
			if(String.isNotEmpty(errStr)){
                stackTrace += '\n'+errStr;
                status = Cst.STATUS_WARNING;
			}
        }catch(Exception e){
            status = Cst.STATUS_ERROR;
            res.statusCode = 400;
            msg = e.getMessage() + e.getStackTraceString();
			stackTrace = e.getStackTraceString();
			res.responseBody = Blob.valueOf(msg+'\n'+stackTrace);
        }

		// Force set Response Status by settings
		if(stt.ForceStatusCode__c != null){ res.statusCode = (Integer)stt.ForceStatusCode__c; msg = 'FORCED STATUS CODE:\n'+msg; }

        SyncUtils.logServiceActivity(SVC_NAME, status, res.statusCode, msg, stackTrace, Hlp.getStringWithLength(body,32000));
        return;
	}
}