force-app/main/default/objects/BOM__c/BOM__c.object-meta.xml
<CustomObject>
    <description>Bill Of Material</description>
    <label>BOM</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BOM__c/fields/BundleId__c.field-meta.xml
<CustomField>
    <fullName>BundleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to bundle master product.</description>
    <inlineHelpText>Relation to bundle master product.</inlineHelpText>
    <label>Bundle</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Items (list of material)</relationshipLabel>
    <relationshipName>BOMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/BundleItemId__c.field-meta.xml
<CustomField>
    <fullName>BundleItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to bundle item product.</description>
    <inlineHelpText>Relation to bundle item product.</inlineHelpText>
    <label>Bundle Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parent Bundles (where is this material used)</relationshipLabel>
    <relationshipName>BOMItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position from SAP</description>
    <inlineHelpText>Position from SAP</inlineHelpText>
    <label>Position</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantity in Bundle.</description>
    <inlineHelpText>Quantity in Bundle.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/QuantityUnitOfMeasure__c.field-meta.xml
<CustomField>
    <fullName>QuantityUnitOfMeasure__c</fullName>
    <label>Quantity Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuantityUnitOfMeasure</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BOM__c/fields/RowNumber__c.field-meta.xml
<CustomField>
    <fullName>RowNumber__c</fullName>
    <label>Row Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Specification__c.field-meta.xml
<CustomField>
    <fullName>Specification__c</fullName>
    <formula>IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;1&quot;),&quot;SPRINKLER&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;2&quot;),&quot;Madlo&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;3&quot;),&quot;Panty&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;4&quot;),&quot;Dveřní těsnění&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;5&quot;),&quot;Zasklívací těsnění&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;6&quot;),&quot;Stolek PRIME&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;7&quot;),&quot;Zdrojový kabel&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;8&quot;),&quot;Zásuvka v panelu - PRIME,UNIQ&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;9&quot;),&quot;Zásuvkový panel 4-modulový volně stojící / na stolku&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;10&quot;),&quot;Čalounění&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;11&quot;),&quot;Výroba&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;12&quot;),&quot;SOFT&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;13&quot;),&quot;AMBIENT&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;14&quot;),&quot;PULSE&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;15&quot;),&quot;Umístění stolku UNIQ&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;16&quot;),&quot;16&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;17&quot;),&quot;17&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;18&quot;),&quot;18&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;19&quot;),&quot;Rám - PRIME&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;20&quot;),&quot;Rám - UNIQ&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;21&quot;),&quot;Rám - CUBIQ&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;22&quot;),&quot;Rám - QI&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;23&quot;),&quot;Rám - QUADRIO&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;24&quot;),&quot;Strop QUADRIO&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;25&quot;),&quot;Umístění stolku PRIME&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;26&quot;),&quot;Zásuvka v panelu - CUBIQ,QI&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;27&quot;),&quot;Zásuvka v panelu QII-QIV&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;28&quot;),&quot;Látka na akustické závěsy&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;29&quot;),&quot;Zásuvka v panelu - SPARK, UNIQ&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;30&quot;),&quot;30&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;31&quot;),&quot;Rám - SPARK&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;32&quot;),&quot;32&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;33&quot;),&quot;Externí opláštění - SPARK&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;34&quot;),&quot;Externí opláštění - SPARK²&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;35&quot;),&quot;Externí opláštění - SPARK⁴&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;36&quot;),&quot;Rám SPARK²/ ⁴&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;37&quot;),&quot;Zásuvka pod stolem / na zemi - SPARK²&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;38&quot;),&quot;Zásuvka ve stolku - SPARK⁴&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;39&quot;),&quot;Zásuvka na zemi- SPARK⁴&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;40&quot;),&quot;Látka interiérových obkladů&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;41&quot;),&quot;Zásuvka ve stolku - SPARK²&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;42&quot;),&quot;Látka sezení SPARK&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;43&quot;),&quot;Příplatek Extra&quot;,NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Specification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(BundleItemId__r.Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/UnitCost__c.field-meta.xml
<CustomField>
    <fullName>UnitCost__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BusinessName__c.field-meta.xml
<CustomField>
    <fullName>BusinessName__c</fullName>
    <label>Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BusinessNameEN__c.field-meta.xml
<CustomField>
    <fullName>BusinessNameEN__c</fullName>
    <label>Business Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if Product is created in SAP and is available for adding to Quote</description>
    <inlineHelpText>Determines if Product is created in SAP and is available for adding to Quote</inlineHelpText>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductDescriptionCZ__c.field-meta.xml
<CustomField>
    <fullName>ProductDescriptionCZ__c</fullName>
    <label>Product Description CZ</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductDescriptionEN__c.field-meta.xml
<CustomField>
    <fullName>ProductDescriptionEN__c</fullName>
    <label>Product Description EN</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/RequestForTechnicianId__c.field-meta.xml
<CustomField>
    <fullName>RequestForTechnicianId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request For Technician</label>
    <referenceTo>RequestForTechnician__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Specification__c.field-meta.xml
<CustomField>
    <fullName>Specification__c</fullName>
    <label>Specification</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductSpecification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M-AKU_PENA</fullName>
            </value>
            <value>
                <fullName>M-BARVY</fullName>
            </value>
            <value>
                <fullName>M-DROBNY_SPMAT</fullName>
            </value>
            <value>
                <fullName>M-ELEKTRO</fullName>
            </value>
            <value>
                <fullName>M-FUKUMA</fullName>
            </value>
            <value>
                <fullName>M-KOV</fullName>
            </value>
            <value>
                <fullName>M-KOVANI</fullName>
            </value>
            <value>
                <fullName>M-LATKA</fullName>
            </value>
            <value>
                <fullName>M-MICROOFFICE</fullName>
            </value>
            <value>
                <fullName>M-OBALY</fullName>
            </value>
            <value>
                <fullName>M-OSTATNI</fullName>
            </value>
            <value>
                <fullName>M-PLOSNY_MAT</fullName>
            </value>
            <value>
                <fullName>M-SKLO</fullName>
            </value>
            <value>
                <fullName>P-POLOTOVAR</fullName>
            </value>
            <value>
                <fullName>S-SKLADOVE SLUZBY</fullName>
            </value>
            <value>
                <fullName>S-SLUZBY</fullName>
            </value>
            <value>
                <fullName>V-VYROBEK</fullName>
            </value>
            <value>
                <fullName>Z-ZBOZI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitCost__c.field-meta.xml
<CustomField>
    <fullName>UnitCost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ProductDescription__c/ProductDescription__c.object-meta.xml
<CustomObject>
    <label>Product Description</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDescription__c/fields/DescriptionCZ__c.field-meta.xml
<CustomField>
    <fullName>DescriptionCZ__c</fullName>
    <label>Description CZ</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ProductDescription__c/fields/DescriptionEN__c.field-meta.xml
<CustomField>
    <fullName>DescriptionEN__c</fullName>
    <label>Description EN</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ProductDescription__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Descriptions</relationshipLabel>
    <relationshipName>ProductDescriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductDescription__c/fields/RowNumber__c.field-meta.xml
<CustomField>
    <fullName>RowNumber__c</fullName>
    <label>Row Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductDescription__c/fields/TitleCZ__c.field-meta.xml
<CustomField>
    <fullName>TitleCZ__c</fullName>
    <label>Title CZ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductDescription__c/fields/TitleEN__c.field-meta.xml
<CustomField>
    <fullName>TitleEN__c</fullName>
    <label>Title EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RequestForTechnician__c/RequestForTechnician__c.object-meta.xml
<CustomObject>
    <label>Request For Technician</label>
    <nameField>
        <displayFormat>RFT-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request For Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestForTechnician__c/fields/QuoteCurrency__c.field-meta.xml
<CustomField>
    <fullName>QuoteCurrency__c</fullName>
    <formula>TEXT(CurrencyIsoCode)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/QuantityUnitOfMeasure.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ks</fullName>
        <default>true</default>
        <label>ks</label>
    </customValue>
    <customValue>
        <fullName>bm</fullName>
    </customValue>
    <customValue>
        <fullName>m2</fullName>
    </customValue>
    <customValue>
        <fullName>kpl</fullName>
    </customValue>
    <customValue>
        <fullName>kg</fullName>
    </customValue>
    <customValue>
        <fullName>g</fullName>
    </customValue>
    <customValue>
        <fullName>pár</fullName>
    </customValue>
    <masterLabel>Quantity Unit of Measure</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NewProductTechniciansController.cls
public without sharing class NewProductTechniciansController  {

	@AuraEnabled
	public static String auraGetInitData(){
		Mdl.RFTInitMdl rftInit = new Mdl.RFTInitMdl();
		rftInit.typePickVals = Hlp.getPickVals('Product2', 'Type__c');
		rftInit.typePickVals.add(0, new Mdl.PickVal('0', '--None--'));
		rftInit.specPickVals = Hlp.getPickVals('Product2', 'Specification__c');
		rftInit.specPickVals.add(0, new Mdl.PickVal('0', '--None--'));
		rftInit.qomPickVals = Hlp.getPickVals('Product2', 'QuantityUnitOfMeasure');
		rftInit.qomPickVals.add(0, new Mdl.PickVal('0', '--None--'));
		rftInit.currncyPickVals = Hlp.getPickVals('Product2', 'CurrencyIsoCode');
		rftInit.currncyPickVals.add(0, new Mdl.PickVal('0', '--None--'));
		rftInit.prodFamilies = Hlp.getPickVals('Product2', 'Family');
		rftInit.prodFamilies.add(0, new Mdl.PickVal('0', '--None--'));
		rftInit.tmpRecordId = [SELECT Id FROM TemporaryRecord__c WHERE Name =:Cst.RFT_TMP_RECORD_NAME LIMIT 1].Id;
		rftInit.guid = Hlp.NewGuid();
		System.debug('typePickVals'+rftInit.typePickVals);
		return JSON.serialize(rftInit);
	}

	@AuraEnabled
	public static String auraGetProductDetail(String prodId){
		Mdl.RFTMdl rftm = new Mdl.RFTMdl();
		if(prodId != null){
			rftm.prod = [SELECT Name, Type__c, CurrencyIsoCode, QuantityUnitOfMeasure, Description, BusinessName__c, BusinessNameEN__c, ProductDescriptionCZ__c, ProductDescriptionEN__c, UnitCost__c, Family FROM Product2 WHERE Id =: prodId ORDER BY Name DESC LIMIT 1];
			rftm.boms = [SELECT Name, BundleId__c, BundleItemId__r.Name, BundleItemId__r.ProductCode, BundleItemId__r.QuantityUnitOfMeasure, Quantity__c, BundleItemId__r.UnitCost__c, Position__c, UnitCost__c, QuantityUnitOfMeasure__c FROM BOM__c WHERE BundleId__c =: prodId];		
			rftm.prodDescs = [SELECT Name, TitleCZ__c, TitleEN__c, DescriptionCZ__c, DescriptionEN__c, RowNumber__c FROM ProductDescription__c WHERE ProductId__c =: prodId];

			Mdl.ProductAttachmentsModel[] pAttM = new Mdl.ProductAttachmentsModel[]{};
			Set<Id> cdIds = new Set<Id>();
			ContentDocumentLink[] cdls = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: prodId];
			for(ContentDocumentLink cdl : cdls){
				cdIds.add(cdl.ContentDocumentId);
			}
			ContentDocument[] cds = [SELECT Title, Id, FileType, LatestPublishedVersionId FROM ContentDocument WHERE Id IN: cdIds]; 
			if(!cds.isEmpty()){
                for(ContentDocument cd : cds){
                    Mdl.ProductAttachmentsModel pam = new Mdl.ProductAttachmentsModel();
                    pam.id = cd.Id;
                    String onlyName = cd.Title;
                    pam.shortName = Hlp.getFormatedSubstring(onlyName, 20);
                    pam.fullName = onlyName + '.' + cd.FileType.toLowerCase();
                    pam.suffix = cd.FileType.toLowerCase();
                    pam.isAttached = false;
                    pam.sendName = Hlp.getFormatedSubstring(onlyName, 15);
                    pam.attachLink = '/sfc/servlet.shepherd/version/download/' + cd.LatestPublishedVersionId;
                    pAttM.add(pam);
                }
            }
			rftm.pAttchMdl = pAttM;
		}else{
			rftm.prod = new Product2(Name = '', Type__c = '0', CurrencyIsoCode = 'CZK', QuantityUnitOfMeasure = '0', Description = '');
		}
		System.debug('RFTModel ' + rftm);
		return JSON.serialize(rftm);
	}

	@AuraEnabled
	public static String auraGetSearchResult(String sType, String sSpec, String sName){

		String query = 'SELECT Name, UnitCost__c, ProductCode, Specification__c, Type__c, QuantityUnitOfMeasure FROM Product2';
		String whereClause = '';

		if(sType != '0'){whereClause += 'Type__c = \'' + sType + '\'';}

		if(sSpec != '0'){
			if(!String.isEmpty(whereClause)){
				whereClause += ' AND Specification__c = \'' + sSpec + '\'';
			}else{
				whereClause += 'Specification__c = \'' + sSpec + '\'';
			}
		}

		if(sName != ''){ 
			System.debug('Name length: ' + sName.length());
			if(!String.isEmpty(whereClause)){
				whereClause += ' AND Name LIKE \'%' + sName + '%\'';
			}else{
				whereClause += 'Name LIKE \'%' + sName + '%\'';
			}
		}

		if(whereClause != ''){
			query += ' WHERE ' + whereClause;
		}
		query += ' ORDER BY Name ASC';
		if(sName.length() < 2){
			query += ' LIMIT 50';
		}
		System.debug('Query ' + query);
		return JSON.serialize(Database.query(query));
	}

	@AuraEnabled
	public static void auraSaveBundle(String rftModel, String bomsToDel, String pdToDel, String recordId, String guid){
		Mdl.RFTMdl rftMdl = (Mdl.RFTMdl)JSON.deserialize(rftModel, Mdl.RFTMdl.class);
		BOM__c[] bomsToDelete = (BOM__c[])JSON.deserialize(bomsToDel, BOM__c[].class);
		ProductDescription__c[] pdsToDelete = (ProductDescription__c[])JSON.deserialize(pdToDel, ProductDescription__c[].class);

		System.debug('RFTMdl ' + rftMdl.prod);

		RequestForTechnician__c req = [SELECT QuoteCurrency__c FROM RequestForTechnician__c WHERE Id =: recordId];

		Decimal totalBOMUnitCost = 0;
		if(rftMdl.boms.size() > 0){
			for(BOM__c bom : rftMdl.boms){
				totalBOMUnitCost += bom.BundleItemId__r.UnitCost__c * bom.Quantity__c;
			}
		}

		rftMdl.prod.RequestForTechnicianId__c = recordId;
		rftMdl.prod.IsActive = true;
		rftMdl.prod.IsDefault__c = true;
		rftMdl.prod.UnitPriceCZK__c = totalBOMUnitCost * 4.5;
		rftMdl.prod.UnitPriceCZK__c = rftMdl.prod.UnitPriceCZK__c.setScale(0);
		CurrencyType ctEur = [SELECT ConversionRate,IsActive,IsoCode FROM CurrencyType WHERE IsoCode = 'EUR' AND IsActive = true];
		rftMdl.prod.UnitPriceEUR__c = totalBOMUnitCost * ctEur.ConversionRate * 4.5;
		rftMdl.prod.UnitPriceEUR__c = rftMdl.prod.UnitPriceEUR__c.setScale(0);
		CurrencyType ctUsd = [SELECT ConversionRate,IsActive,IsoCode FROM CurrencyType WHERE IsoCode = 'USD' AND IsActive = true];
		rftMdl.prod.UnitPriceUSD__c = totalBOMUnitCost * ctUsd.ConversionRate * 4.5;
		rftMdl.prod.UnitPriceUSD__c = rftMdl.prod.UnitPriceUSD__c.setScale(0);

		upsert rftMdl.prod;

		for(BOM__c bom : rftMdl.boms){
			bom.BundleId__c = rftMdl.prod.Id;
		}
		upsert rftMdl.boms;

		for(ProductDescription__c pd: rftMdl.prodDescs){
			pd.Name = pd.TitleCZ__c;
			pd.ProductId__c = rftMdl.prod.Id;
		}
		upsert rftMdl.prodDescs;

		delete bomsToDelete;
		delete pdsToDelete;


		Boolean isInsertSuccess = true;
		ContentVersion[] cvs = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE IsLatest = true AND RefId__c =: guid];

		Set<String> cdIds = new Set<String>();
		if(cvs.size() > 0){
	        for(ContentVersion cv : cvs){
	            cdIds.add(cv.ContentDocumentId);
	        }				
		}
		String tmpRecordId = [SELECT Id FROM TemporaryRecord__c WHERE Name =:Cst.RFT_TMP_RECORD_NAME LIMIT 1].Id;
        if(!cdIds.isEmpty()){
			System.debug('Content Document Ids ' + cdIds);
            ContentDocumentLink[] cdlToDel = [SELECT Id,ContentDocumentId FROM ContentDocumentLink WHERE ContentDocumentId IN :cdIds AND LinkedEntityId =: tmpRecordId];
            ContentDocumentLink[] cdlToInsert = new List<ContentDocumentLink>();
                
            // Create ContentDomumentLink to FormInquory for all files with association with System Lead
            for(ContentDocumentLink cdl : cdlToDel){
                // cerate CDL to FormInquiry
                ContentDocumentLink tmpCdl = new ContentDocumentLink();
                tmpCdl.ContentDocumentId = cdl.ContentDocumentId;
                tmpCdl.LinkedEntityId = rftMdl.prod.Id;
                tmpCdl.ShareType = 'V';
                cdlToInsert.add(tmpCdl);
            }
            System.debug('New CDLs: ' + cdlToInsert);
            Database.SaveResult[] cdlResult = Database.insert(cdlToInsert, true);

            // check if insert was succesfull
            for(Database.SaveResult sr : cdlResult){
                if(!sr.isSuccess()){
                    isInsertSuccess = false;
                }
            }

            // delete ContentDocumentLink to System RFT after succesfull link to Product
            if(isInsertSuccess){
                delete cdlToDel;
            }
        }
	}

	@AuraEnabled
	public static String auraUploadFile(String[] docIds, String guid){
		ContentVersion[] cvs = new ContentVersion[]{};
		Mdl.ProductAttachmentsModel[] pAttM = new Mdl.ProductAttachmentsModel[]{};

		ContentDocument[] cds = [SELECT LatestPublishedVersionId, Title FROM ContentDocument WHERE Id IN: docIds];
		System.debug('ContentDocument' + cds);
		if(cds.size() > 0){
			for(ContentDocument cd : cds){	
				ContentVersion cv = new ContentVersion(Id = cd.LatestPublishedVersionId, RefId__c = guid);
				cvs.add(cv);

				// Generate View/Download Link
				Mdl.ProductAttachmentsModel pam = new Mdl.ProductAttachmentsModel();
                pam.id = cd.Id;
                pam.name = cd.Title;
                pam.attachLink = '/portal/sfc/servlet.shepherd/version/download/' + cd.LatestPublishedVersionId;
                pAttM.add(pam);
			}
			update cvs;
		}
		System.debug('Prod Attachments'+ pAttM);
		return JSON.serialize(pAttM);
	}

	@AuraEnabled
	public static void auraRemoveContentDocument(String attachId){
		ContentDocument cd = new ContentDocument(Id = attachId);
		delete cd;
	}
}