force-app/main/default/objects/BOM__c/BOM__c.object-meta.xml
<CustomObject>
    <description>Bill Of Material</description>
    <label>BOM</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BOM__c/fields/BundleId__c.field-meta.xml
<CustomField>
    <fullName>BundleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to bundle master product.</description>
    <inlineHelpText>Relation to bundle master product.</inlineHelpText>
    <label>Bundle</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Items (list of material)</relationshipLabel>
    <relationshipName>BOMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/BundleItemId__c.field-meta.xml
<CustomField>
    <fullName>BundleItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to bundle item product.</description>
    <inlineHelpText>Relation to bundle item product.</inlineHelpText>
    <label>Bundle Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parent Bundles (where is this material used)</relationshipLabel>
    <relationshipName>BOMItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantity in Bundle.</description>
    <inlineHelpText>Quantity in Bundle.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <label>SAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <externalId>true</externalId>
    <label>SAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceCZK__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceCZK__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price CZK</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceEUR__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceEUR__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price EUR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/RowTotalPrice__c.field-meta.xml
<CustomField>
    <fullName>RowTotalPrice__c</fullName>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/QuoteLineSubItem__c.object-meta.xml
<CustomObject>
    <label>Quote Line Sub Item</label>
    <nameField>
        <label>Quote Line Sub Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Sub Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLineSubItem__c/fields/QuoteLineItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItemId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Quote Line Sub Items</relationshipLabel>
    <relationshipName>QuoteLineSubItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SyncServiceSettings__c/SyncServiceSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SyncServiceSettings</label>
</CustomObject>

force-app/main/default/objects/SyncServiceSettings__c/fields/DisableSync__c.field-meta.xml
<CustomField>
    <fullName>DisableSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <description>Must be set manually by administrator</description>
    <externalId>true</externalId>
    <inlineHelpText>Must be set manually by administrator</inlineHelpText>
    <label>SAP ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/QuoteManagerControllerTest.cls
@isTest 
private class QuoteManagerControllerTest {

    @isTest
    private static void auraGetDataTest() { 
        
		Opportunity o = new Opportunity(Name = 'Test', CloseDate = System.today(), StageName = 'Qualification');
		insert o;
        Quote q = new Quote(Name = 'test', OpportunityId = o.Id);
		insert q;
        // auraGetData Test
        SyncServiceSettings__c stt = new SyncServiceSettings__c();
        stt.Name = 'AccountToSAP';
        stt.DisableSync__c = true;
        insert stt;
        Profile[] prof = [SELECT Id FROM Profile];
        User u = new User(LastName = 'test', ProfileId = prof[0].Id, Username='test@silentlab.cz', EmailEncodingKey = 'UTF-8', Email='test@test.cz', Alias='test', CommunityNickname='test', TimeZoneSidKey='Europe/Berlin', LocaleSidKey='en_US', LanguageLocaleKey='en_US');
        insert u;
        Product2 prod = new Product2(Name='MICRO OFFICE',IsActive=true,ProductCode='ABCD',SAPId__c='A0123',UnitPriceCZK__c=1000,UnitPriceEUR__c=20);
        insert prod;
        Product2 subProd = new Product2(Name='Cloth for MO',IsActive=true,ProductCode='CFMO',SAPId__c='A0456');
        insert subProd;
        BOM__c bom = new BOM__c(BundleId__c=prod.Id,BundleItemId__c=subProd.Id,Quantity__c=10);
        insert bom;

        Id pricebookId = Test.getStandardPricebookId();
        String currForTest = Cst.CURR_CZK;

        // Update product price for EUR
        prod.UnitPriceEUR__c = 15;
        update prod;

        PricebookEntry pbe = [SELECT Id FROM PricebookEntry WHERE Product2Id=:prod.Id AND CurrencyIsoCode=:currForTest LIMIT 1];
        
        Account acc = new Account(Name='Test',BillingCity='Praha');
        insert acc; 
        Opportunity opp = new Opportunity(StageName='Qualification', Name='Opp Test', CloseDate=Date.newInstance(2019, 8, 24), AccountId = acc.Id); 
        insert opp;
        Quote qt = new Quote(Name='Quote Test', OpportunityId=opp.Id, Pricebook2Id = pricebookId);
        insert qt;
        QuoteLineItem qli = new QuoteLineItem(QuoteId=qt.Id, Quantity=10, UnitPrice=10, Product2Id=prod.Id, PricebookEntryId = pbe.Id);
        insert qli;
        QuoteLineItem qli2 = new QuoteLineItem(QuoteId=qt.Id, Quantity=10, UnitPrice=10, RowTotalPrice__c = 0, Product2Id=prod.Id, PricebookEntryId = pbe.Id);
        insert qli2;
        QuoteLineSubItem__c qlsi = new QuoteLineSubItem__c(QuoteLineItemId__c=qli.Id);
        insert qlsi;
        QuoteManagerController.auraGetData(qt.Id);
    
        
        // auraSave Test
        Mdl.QuoteLineMdl[] qmm = new Mdl.QuoteLineMdl[]{};
        String qmmString = JSON.serialize(qmm);
        Mdl.QuoteLineMdl[] qmms = new Mdl.QuoteLineMdl[]{};
        String quoteString = JSON.serialize(qt);
        String transportString = JSON.serialize(qli2);
        QuoteManagerController.auraSave(qmmString, qmms, quoteString, transportString, false, 100);
        QuoteManagerController.auraSave(qmmString, qmms, quoteString, transportString, true, 100);


        // auraGetProdDescs Test
        QuoteManagerController.auraGetProductMdl(prod.Id, currForTest);

        // auraGetNewProduct Test
        QuoteManagerController.auraGetProductByPBE(prod.Id, currForTest);
        
        // auraGetCZKReward Test
        QuoteManagerController.auraGetCZKReward(1000, 'CZK');
    }
}