force-app/main/default/objects/BOM__c/BOM__c.object-meta.xml
<CustomObject>
    <description>Bill Of Material</description>
    <label>BOM</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BOM__c/fields/BundleId__c.field-meta.xml
<CustomField>
    <fullName>BundleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to bundle master product.</description>
    <inlineHelpText>Relation to bundle master product.</inlineHelpText>
    <label>Bundle</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Items (list of material)</relationshipLabel>
    <relationshipName>BOMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/BundleItemId__c.field-meta.xml
<CustomField>
    <fullName>BundleItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to bundle item product.</description>
    <inlineHelpText>Relation to bundle item product.</inlineHelpText>
    <label>Bundle Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parent Bundles (where is this material used)</relationshipLabel>
    <relationshipName>BOMItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantity in Bundle.</description>
    <inlineHelpText>Quantity in Bundle.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/UnitCost__c.field-meta.xml
<CustomField>
    <fullName>UnitCost__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/RefId__c.field-meta.xml
<CustomField>
    <fullName>RefId__c</fullName>
    <externalId>true</externalId>
    <label>Reference ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/RequestForTechnicianId__c.field-meta.xml
<CustomField>
    <fullName>RequestForTechnicianId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request For Technician</label>
    <referenceTo>RequestForTechnician__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitCost__c.field-meta.xml
<CustomField>
    <fullName>UnitCost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ProductDescription__c/ProductDescription__c.object-meta.xml
<CustomObject>
    <label>Product Description</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Descriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductDescription__c/fields/TitleCZ__c.field-meta.xml
<CustomField>
    <fullName>TitleCZ__c</fullName>
    <label>Title CZ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RequestForTechnician__c/RequestForTechnician__c.object-meta.xml
<CustomObject>
    <label>Request For Technician</label>
    <nameField>
        <displayFormat>RFT-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request For Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TemporaryRecord__c/TemporaryRecord__c.object-meta.xml
<CustomObject>
    <label>Temporary Record</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Temporary Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NewProductTechniciansControllerTest.cls
@isTest
public class NewProductTechniciansControllerTest {
	@isTest
    public static void testMethodS() {
		TemporaryRecord__c tmprec = new TemporaryRecord__c(Name = Cst.RFT_TMP_RECORD_NAME);
		insert tmprec;
		NewProductTechniciansController.auraGetInitData();
        RequestForTechnician__c req = new RequestForTechnician__c();
        insert req;
        Product2 prod1 = new Product2(Name='Product', IsActive=true, RequestForTechnicianId__c=req.Id);
        insert prod1;
        Product2 prod2 = new Product2(Name='Product2', IsActive=true, UnitCost__c=100.00);
        insert prod2;
        NewProductTechniciansController.auraGetProductDetail(prod1.Id);
        NewProductTechniciansController.auraGetProductDetail(null);
        NewProductTechniciansController.auraGetSearchResult('M-AKU_PENA', '1', 'AAA');
        Mdl.RFTMdl model = new Mdl.RFTMdl();
        model.prod = prod1;
        BOM__c[] bom = new BOM__c[]{new BOM__c (BundleId__c=prod1.Id,BundleItemId__c=prod2.Id, Quantity__c=2)};
        insert bom;
		ProductDescription__c[] pds = new ProductDescription__c[]{new ProductDescription__c(TitleCZ__c = 'Test', Name = 'test')};
		insert pds;
        
		String guid = Hlp.NewGuid();
		ContentVersion cv = new ContentVersion(VersionData = Blob.valueOf('ngadgnk'), Title = 'TestVersion', PathOnClient = 'PathOnClient', RefId__c = guid);
		insert cv;
		ContentVersion cvm = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id];
		String[] cdIds = new String[]{};
		cdIds.add(cvm.ContentDocumentId);

        NewProducttechniciansController.auraSaveBundle(JSON.serialize(model), JSON.serialize(bom), JSON.serialize(pds), req.Id, guid);
		NewProducttechniciansController.auraUploadFile(cdIds ,guid);
    }
}