force-app/main/default/objects/BOM__c/BOM__c.object-meta.xml
<CustomObject>
    <description>Bill Of Material</description>
    <label>BOM</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BOM__c/fields/BundleId__c.field-meta.xml
<CustomField>
    <fullName>BundleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to bundle master product.</description>
    <inlineHelpText>Relation to bundle master product.</inlineHelpText>
    <label>Bundle</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Items (list of material)</relationshipLabel>
    <relationshipName>BOMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/BundleItemId__c.field-meta.xml
<CustomField>
    <fullName>BundleItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to bundle item product.</description>
    <inlineHelpText>Relation to bundle item product.</inlineHelpText>
    <label>Bundle Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parent Bundles (where is this material used)</relationshipLabel>
    <relationshipName>BOMItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/BundleItemSAPId__c.field-meta.xml
<CustomField>
    <fullName>BundleItemSAPId__c</fullName>
    <description>Kód artiklu ze SAP - dílec (materiál)</description>
    <inlineHelpText>Kód artiklu ze SAP - dílec (materiál)</inlineHelpText>
    <label>Bundle Item SAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/BundleSAPId__c.field-meta.xml
<CustomField>
    <fullName>BundleSAPId__c</fullName>
    <description>Kód Artiklu v SAP (nadřazený výrobek)</description>
    <inlineHelpText>Kód Artiklu v SAP (nadřazený výrobek)</inlineHelpText>
    <label>Bundle SAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position from SAP</description>
    <inlineHelpText>Position from SAP</inlineHelpText>
    <label>Position</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantity in Bundle.</description>
    <inlineHelpText>Quantity in Bundle.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/QuantityUnitOfMeasure__c.field-meta.xml
<CustomField>
    <fullName>QuantityUnitOfMeasure__c</fullName>
    <label>Quantity Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuantityUnitOfMeasure</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/BOM__c/fields/RowNumber__c.field-meta.xml
<CustomField>
    <fullName>RowNumber__c</fullName>
    <label>Row Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <label>SAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Specification__c.field-meta.xml
<CustomField>
    <fullName>Specification__c</fullName>
    <formula>IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;1&quot;),&quot;SPRINKLER&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;2&quot;),&quot;Madlo&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;3&quot;),&quot;Panty&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;4&quot;),&quot;Dveřní těsnění&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;5&quot;),&quot;Zasklívací těsnění&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;6&quot;),&quot;Stolek PRIME&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;7&quot;),&quot;Zdrojový kabel&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;8&quot;),&quot;Zásuvka v panelu - PRIME,UNIQ&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;9&quot;),&quot;Zásuvkový panel 4-modulový volně stojící / na stolku&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;10&quot;),&quot;Čalounění&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;11&quot;),&quot;Výroba&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;12&quot;),&quot;SOFT&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;13&quot;),&quot;AMBIENT&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;14&quot;),&quot;PULSE&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;15&quot;),&quot;Umístění stolku UNIQ&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;16&quot;),&quot;16&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;17&quot;),&quot;17&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;18&quot;),&quot;18&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;19&quot;),&quot;Rám - PRIME&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;20&quot;),&quot;Rám - UNIQ&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;21&quot;),&quot;Rám - CUBIQ&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;22&quot;),&quot;Rám - QI&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;23&quot;),&quot;Rám - QUADRIO&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;24&quot;),&quot;Strop QUADRIO&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;25&quot;),&quot;Umístění stolku PRIME&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;26&quot;),&quot;Zásuvka v panelu - CUBIQ,QI&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;27&quot;),&quot;Zásuvka v panelu QII-QIV&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;28&quot;),&quot;Látka na akustické závěsy&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;29&quot;),&quot;Zásuvka v panelu - SPARK, UNIQ&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;30&quot;),&quot;30&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;31&quot;),&quot;Rám - SPARK&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;32&quot;),&quot;32&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;33&quot;),&quot;Externí opláštění - SPARK&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;34&quot;),&quot;Externí opláštění - SPARK²&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;35&quot;),&quot;Externí opláštění - SPARK⁴&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;36&quot;),&quot;Rám SPARK²/ ⁴&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;37&quot;),&quot;Zásuvka pod stolem / na zemi - SPARK²&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;38&quot;),&quot;Zásuvka ve stolku - SPARK⁴&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;39&quot;),&quot;Zásuvka na zemi- SPARK⁴&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;40&quot;),&quot;Látka interiérových obkladů&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;41&quot;),&quot;Zásuvka ve stolku - SPARK²&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;42&quot;),&quot;Látka sezení SPARK&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;43&quot;),&quot;Příplatek Extra&quot;,NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Specification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(BundleItemId__r.Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/UnitCost__c.field-meta.xml
<CustomField>
    <fullName>UnitCost__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BusinessNameEN__c.field-meta.xml
<CustomField>
    <fullName>BusinessNameEN__c</fullName>
    <label>Business Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <externalId>true</externalId>
    <label>SAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Specification__c.field-meta.xml
<CustomField>
    <fullName>Specification__c</fullName>
    <label>Specification</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductSpecification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SyncStatus__c.field-meta.xml
<CustomField>
    <fullName>SyncStatus__c</fullName>
    <label>Sync Status (System)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SyncStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M-AKU_PENA</fullName>
            </value>
            <value>
                <fullName>M-BARVY</fullName>
            </value>
            <value>
                <fullName>M-DROBNY_SPMAT</fullName>
            </value>
            <value>
                <fullName>M-ELEKTRO</fullName>
            </value>
            <value>
                <fullName>M-FUKUMA</fullName>
            </value>
            <value>
                <fullName>M-KOV</fullName>
            </value>
            <value>
                <fullName>M-KOVANI</fullName>
            </value>
            <value>
                <fullName>M-LATKA</fullName>
            </value>
            <value>
                <fullName>M-MICROOFFICE</fullName>
            </value>
            <value>
                <fullName>M-OBALY</fullName>
            </value>
            <value>
                <fullName>M-OSTATNI</fullName>
            </value>
            <value>
                <fullName>M-PLOSNY_MAT</fullName>
            </value>
            <value>
                <fullName>M-SKLO</fullName>
            </value>
            <value>
                <fullName>P-POLOTOVAR</fullName>
            </value>
            <value>
                <fullName>S-SKLADOVE SLUZBY</fullName>
            </value>
            <value>
                <fullName>S-SLUZBY</fullName>
            </value>
            <value>
                <fullName>V-VYROBEK</fullName>
            </value>
            <value>
                <fullName>Z-ZBOZI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitCost__c.field-meta.xml
<CustomField>
    <fullName>UnitCost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceCZK__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceCZK__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price CZK</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceEUR__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceEUR__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price EUR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceUSD__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceUSD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price USD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SyncServiceSettings__c/SyncServiceSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SyncServiceSettings</label>
</CustomObject>

force-app/main/default/objects/SyncServiceSettings__c/fields/DisableSync__c.field-meta.xml
<CustomField>
    <fullName>DisableSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/QuantityUnitOfMeasure.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ks</fullName>
        <default>true</default>
        <label>ks</label>
    </customValue>
    <customValue>
        <fullName>bm</fullName>
    </customValue>
    <customValue>
        <fullName>m2</fullName>
    </customValue>
    <customValue>
        <fullName>kpl</fullName>
    </customValue>
    <customValue>
        <fullName>kg</fullName>
    </customValue>
    <customValue>
        <fullName>g</fullName>
    </customValue>
    <customValue>
        <fullName>pár</fullName>
    </customValue>
    <masterLabel>Quantity Unit of Measure</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SyncStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SUCCESS</fullName>
    </customValue>
    <customValue>
        <fullName>WARNING</fullName>
    </customValue>
    <customValue>
        <fullName>ERROR</fullName>
    </customValue>
    <customValue>
        <fullName>SYNCING</fullName>
    </customValue>
    <customValue>
        <fullName>FORCE</fullName>
    </customValue>
    <customValue>
        <fullName>HOLD</fullName>
    </customValue>
    <masterLabel>Sync Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Svc_ProductToSAP.cls
public class Svc_ProductToSAP implements Queueable, Database.AllowsCallouts {
	private static String SVC_NAME = 'ProductToSAP';
	
	public Set<Id> recIds{get;set;}
	public Set<Id> ordrIds{get;set;}

	public Svc_ProductToSAP(Set<Id> rIds, Set<Id> oIds){
		recIds = rIds;
		ordrIds = oIds;
	}

    public void execute(QueueableContext qc) {
		syncToSAP(recIds, ordrIds);
	}

	public static void syncToSAP(Set<Id> recIds, Set<Id> orderIds){
		SyncServiceSettings__c stt = SyncServiceSettings__c.getValues(SVC_NAME);
        if(stt.DisableSync__c){ SyncUtils.logServiceActivity(SVC_NAME, Cst.STATUS_ERROR, 503, 'ERROR: Service is disabled'); return; }
		try{
			//SyncUtils.validateAccess(SVC_NAME);
    		Set<Id> chldRecIds = new Set<Id>();
			Product2[] prods = [SELECT
								BusinessNameEN__c,
								Description,
								Family, // V, Výrobek | M, Materiál | P, Polotovar | Z, Zboží | S, Služby
										// Skupina artiklů. Dle počátečního písmena skupiny artiklů lze rozlišit,
										// o kterou kategorii se jedná. Například M-Dřevo je materiál. V-Výrobek je pak výrobek, atd.
								Id,
								IsActive,
								Name,
								ProductCode, // Kód artiklu v Salesforce (Pro nově vzniklé výrobky v SF)
								QuantityUnitOfMeasure,
								Specification__c, // Multiselect picklist = hodnota se přenáší do ItemAttributes
								Type__c, // Typ produktu (Standard Bundle, Product, Custom Bundle)
								UnitCost__c, // Nákladová cena za kus. Vždy v CZK (currency ISO code).
								UnitPriceCZK__c, // Prodejní cena za kus v CZK.	Prodejní cena z ceníku 1
								UnitPriceUSD__c, // Prodejní cena za kus v USD.	Prodejní cena z ceníku 1 - doplňková měna 1
								UnitPriceEUR__c, // Prodejní cena za kus v EUR.	Prodejní cena z ceníku 1 - doplňková měna 2
								SAPId__c,
								(SELECT
									BundleId__c, 
									BundleSAPId__c, // Kód artiklu ze SAP - (nadřazený výrobek)
									BundleItemId__c,
									BundleItemSAPId__c, // Kód artiklu ze SAP - (/materiál)
									Id,
									//Name,	
									Quantity__c, // Množství.	Množství materiálu na 1KS nadřazeného výrobku
									QuantityUnitOfMeasure__c, // MJ.	Skladová měrná jednotka
									RowNumber__c, // Číslo řádku v kusovníku.	Číslo řádku v kusovníku
									Type__c, // Např. MAX-MATERIAL atd...
									Position__c // Označení pozice výroby - text (čalouníci, montáž, 1, 2 atd. - může být označeno názvem nebo číslem)
									FROM BOMs__r)
								FROM Product2 WHERE Id IN:recIds];

			for(Product2 chP : prods){
				for(BOM__c bom : chP.BOMs__r){
					if(!recIds.contains(bom.BundleItemId__c)){
						chldRecIds.add(bom.BundleItemId__c);
					}
				}
			}
			Product2[] recs = [SELECT Description, Family, Id, IsActive, Name, ProductCode, QuantityUnitOfMeasure, Specification__c, Type__c, UnitCost__c, UnitPriceCZK__c, UnitPriceUSD__c, UnitPriceEUR__c, SAPId__c
								FROM Product2 WHERE Id IN:chldRecIds];
			recs.addAll(prods);

			// Convert Specification__c to SAP format
			for(Product2 p : recs){
				p.Specification__c = SyncUtils.productSpecificationToItemAttributes(p.Specification__c);
			}

			String dataStr = JSON.serialize(recs, false);
			HttpResponse res = SyncUtils.sendData(SVC_NAME, dataStr);
			String respBody = res.getBody();
			String status;
			if(res.getStatusCode() == 200){
				status = Cst.STATUS_SUCCESS;
				SyncUtils.logServiceActivity(SVC_NAME, Cst.STATUS_SUCCESS, res.getStatusCode(), 'SUCCESS: products synced ('+String.join(new List<Id>(recIds),', ')+')', null, dataStr, respBody);
			}else{
				status = Cst.STATUS_ERROR;
				SyncUtils.logServiceActivity(SVC_NAME, Cst.STATUS_ERROR, res.getStatusCode(), 'ERROR - something wents wrong: ' + res.getStatus(), res.getBody(), dataStr, respBody);
			}
		
			Map<Id,String> respMap = new Map<Id,String>();
			try{
				Mdl.SAPResponse[] respRecs = (Mdl.SAPResponse[])JSON.deserialize(SyncUtils.getValidJsonForCustomModel(respBody), Mdl.SAPResponse[].class);
				for(Mdl.SAPResponse r : respRecs){
					respMap.put(r.Id, r.SAPId);
				}
			}catch(Exception ex){
				status = Cst.STATUS_WARNING;
				SyncUtils.logServiceActivity(SVC_NAME, Cst.STATUS_WARNING, res.getStatusCode(), 'WARNING - response was not parsed: '+ex.getMessage(), ex.getStackTraceString(), null, respBody);
			}

			// Set result recs
			Product2[] prodsToUpdate = new Product2[]{};
			for(Product2 p : recs){
				Product2 np = new Product2();
				np.Id = p.Id;
				np.SyncStatus__c = status;
				String sapId = respMap.get(p.Id);
				if(sapId != null){
					np.SAPID__c = sapId;
				}
				prodsToUpdate.add(np);
			}
			update prodsToUpdate;
			// Also set related Orders for Sync
			if(orderIds != null && !orderIds.isEmpty()){
				System.enqueueJob(new Svc_OrderToSAP(orderIds)); // If success and Ids defined - call next job
			}
		}catch(Exception e){
			SyncUtils.logServiceActivity(SVC_NAME, Cst.STATUS_ERROR, 0, e.getMessage(), e.getStackTraceString());
		}
	}

    public static void sendData(Set<Id> recIds, Set<Id> orderIds){

	}
}