force-app/main/default/objects/BOM__c/BOM__c.object-meta.xml
<CustomObject>
    <description>Bill Of Material</description>
    <label>BOM</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BOM__c/fields/BundleId__c.field-meta.xml
<CustomField>
    <fullName>BundleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to bundle master product.</description>
    <inlineHelpText>Relation to bundle master product.</inlineHelpText>
    <label>Bundle</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bundle Items (list of material)</relationshipLabel>
    <relationshipName>BOMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/BundleItemId__c.field-meta.xml
<CustomField>
    <fullName>BundleItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relation to bundle item product.</description>
    <inlineHelpText>Relation to bundle item product.</inlineHelpText>
    <label>Bundle Item</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parent Bundles (where is this material used)</relationshipLabel>
    <relationshipName>BOMItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantity in Bundle.</description>
    <inlineHelpText>Quantity in Bundle.</inlineHelpText>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <label>SAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM__c/fields/Specification__c.field-meta.xml
<CustomField>
    <fullName>Specification__c</fullName>
    <formula>IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;1&quot;),&quot;SPRINKLER&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;2&quot;),&quot;Madlo&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;3&quot;),&quot;Panty&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;4&quot;),&quot;Dveřní těsnění&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;5&quot;),&quot;Zasklívací těsnění&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;6&quot;),&quot;Stolek PRIME&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;7&quot;),&quot;Zdrojový kabel&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;8&quot;),&quot;Zásuvka v panelu - PRIME,UNIQ&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;9&quot;),&quot;Zásuvkový panel 4-modulový volně stojící / na stolku&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;10&quot;),&quot;Čalounění&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;11&quot;),&quot;Výroba&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;12&quot;),&quot;SOFT&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;13&quot;),&quot;AMBIENT&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;14&quot;),&quot;PULSE&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;15&quot;),&quot;Umístění stolku UNIQ&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;16&quot;),&quot;16&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;17&quot;),&quot;17&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;18&quot;),&quot;18&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;19&quot;),&quot;Rám - PRIME&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;20&quot;),&quot;Rám - UNIQ&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;21&quot;),&quot;Rám - CUBIQ&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;22&quot;),&quot;Rám - QI&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;23&quot;),&quot;Rám - QUADRIO&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;24&quot;),&quot;Strop QUADRIO&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;25&quot;),&quot;Umístění stolku PRIME&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;26&quot;),&quot;Zásuvka v panelu - CUBIQ,QI&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;27&quot;),&quot;Zásuvka v panelu QII-QIV&quot; + BR(),NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;28&quot;),&quot;Látka na akustické závěsy&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;29&quot;),&quot;Zásuvka v panelu - SPARK, UNIQ&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;30&quot;),&quot;30&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;31&quot;),&quot;Rám - SPARK&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;32&quot;),&quot;32&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;33&quot;),&quot;Externí opláštění - SPARK&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;34&quot;),&quot;Externí opláštění - SPARK²&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;35&quot;),&quot;Externí opláštění - SPARK⁴&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;36&quot;),&quot;Rám SPARK²/ ⁴&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;37&quot;),&quot;Zásuvka pod stolem / na zemi - SPARK²&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;38&quot;),&quot;Zásuvka ve stolku - SPARK⁴&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;39&quot;),&quot;Zásuvka na zemi- SPARK⁴&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;40&quot;),&quot;Látka interiérových obkladů&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;41&quot;),&quot;Zásuvka ve stolku - SPARK²&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;42&quot;),&quot;Látka sezení SPARK&quot;,NULL)+
IF(INCLUDES(BundleItemId__r.Specification__c ,&quot;43&quot;),&quot;Příplatek Extra&quot;,NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Specification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CNBRatesSyncSettings__c/CNBRatesSyncSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CNB Rates Sync Settings</label>
</CustomObject>

force-app/main/default/objects/CNBRatesSyncSettings__c/fields/isAdvancedCurrRateSync__c.field-meta.xml
<CustomField>
    <fullName>isAdvancedCurrRateSync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is advanced currency rate sync enabled.</description>
    <label>isAdvancedCurrRateSync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GoogleDriveAuth__c/GoogleDriveAuth__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Google Drive Auth</label>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/IsProforma__c.field-meta.xml
<CustomField>
    <fullName>IsProforma__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proforma</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <externalId>true</externalId>
    <label>SAP ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/RequestForTechnicianId__c.field-meta.xml
<CustomField>
    <fullName>RequestForTechnicianId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request For Technician</label>
    <referenceTo>RequestForTechnician__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <externalId>true</externalId>
    <label>SAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Specification__c.field-meta.xml
<CustomField>
    <fullName>Specification__c</fullName>
    <label>Specification</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductSpecification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceCZK__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceCZK__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price CZK</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceEUR__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceEUR__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price EUR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DescriptionForTechnician__c.field-meta.xml
<CustomField>
    <fullName>DescriptionForTechnician__c</fullName>
    <label>Description for Technician</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/QuoteLineSubItem__c.object-meta.xml
<CustomObject>
    <label>Quote Line Sub Item</label>
    <nameField>
        <label>Quote Line Sub Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Sub Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLineSubItem__c/fields/QuoteLineItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItemId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Quote Line Sub Items</relationshipLabel>
    <relationshipName>QuoteLineSubItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestForTechnician__c/RequestForTechnician__c.object-meta.xml
<CustomObject>
    <label>Request For Technician</label>
    <nameField>
        <displayFormat>RFT-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request For Technicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestForTechnician__c/fields/DescriptionForTechnician__c.field-meta.xml
<CustomField>
    <fullName>DescriptionForTechnician__c</fullName>
    <label>Description For Technician</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RequestForTechnician__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Name</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Request For Technicians</relationshipLabel>
    <relationshipName>RequestForTechnicians</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestForTechnician__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RequestStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/RequestStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Requested</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Done</fullName>
    </customValue>
    <description>Request For Technician</description>
    <masterLabel>Request Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Svc_OppCSVExportTestSuite.cls
@isTest
public class Svc_OppCSVExportTestSuite  {
	@IsTest
	public static void SchedulableTests(){
		OppCSVExportSchedulable1.scheduleJob();
		OppCSVExportSchedulable1.cancel();

		OppCSVExportSchedulable2.scheduleJob();
		OppCSVExportSchedulable2.cancel();

		OppCSVExportSchedulable3.scheduleJob();
		OppCSVExportSchedulable3.cancel();

		OppCSVExportSchedulable4.scheduleJob();
		OppCSVExportSchedulable4.cancel();
	}

	@isTest
	public static void Svc_OppCSVExportTest(){
		Svc_OppCSVExport.exportOppsToGdrive();
	}

	@isTest
	public static void Svc_OppCSVExportTest2(){
		GoogleDriveAuth__c sett = new GoogleDriveAuth__c(Name='default', TokenExpireDate__c = System.now().addDays(1));
		insert sett;
		Test.startTest();
		
		Product2 prod = new Product2(Name='MICRO OFFICE',IsActive=true,ProductCode='ABCD',SAPId__c='A0123',UnitPriceCZK__c=1000,UnitPriceEUR__c=20);
		insert prod;
		Product2 subProd = new Product2(Name='Cloth for MO',IsActive=true,ProductCode='CFMO',SAPId__c='A0456', Specification__c= '10;11');
		insert subProd;
		BOM__c bom = new BOM__c(BundleId__c=prod.Id,BundleItemId__c=subProd.Id,Quantity__c=10);
		insert bom;

		Id pricebookId = Test.getStandardPricebookId();
		String currForTest = Cst.CURR_CZK;

		// Update product price for EUR
		prod.UnitPriceEUR__c = 15;
		update prod;

		PricebookEntry pbe = [SELECT Id FROM PricebookEntry WHERE Product2Id=:prod.Id AND CurrencyIsoCode=:currForTest LIMIT 1];
		
		Opportunity opp = new Opportunity(StageName='Qualification', Name='Opp Test', CloseDate=Date.newInstance(2019, 8, 24));	
		insert opp;
		Quote qt = new Quote(Name='Quote Test', OpportunityId=opp.Id, Pricebook2Id = pricebookId);
		insert qt;
		opp.SyncedQuoteId = qt.Id;
		update opp;
		RequestForTechnician__c rft = new RequestForTechnician__c(DescriptionForTechnician__c = 'Test', QuoteId__c = qt.Id, Status__c='Done', CurrencyIsoCode=opp.CurrencyIsoCode);
		insert rft;
		Product2 prod2 = new Product2(Name='MICRO OFFICE',IsActive=true,ProductCode='ABCD',SAPId__c='A0123',UnitPriceCZK__c=1000,UnitPriceEUR__c=20, RequestForTechnicianId__c = rft.Id);
		insert prod2;
		rft.Status__c = Cst.RFT_STATUS_DONE;
		update rft;

		QuoteLineItem qli = new QuoteLineItem(QuoteId=qt.Id, Quantity=10, UnitPrice=10, Product2Id=prod.Id, PricebookEntryId = pbe.Id);
		insert qli;
		QuoteLineSubItem__c qlsi = new QuoteLineSubItem__c(QuoteLineItemId__c=qli.Id);
		insert qlsi;
		Invoice__c inv = new Invoice__c(OpportunityId__c = opp.Id, IsProforma__c = true);
		insert inv;

		Svc_OppCSVExport.exportOppsToGdrive();
		Test.stopTest();
	}


	@isTest
	public static void Svc_OppCSVExportTest3(){
		GoogleDriveAuth__c sett = new GoogleDriveAuth__c(Name='default', TokenExpireDate__c = System.now().addDays(1));
		insert sett;
		CNBRatesSyncSettings__c sett2 = new CNBRatesSyncSettings__c(Name ='default', isAdvancedCurrRateSync__c = true);
		insert sett2;
		Test.startTest();
		
		Product2 prod = new Product2(Name='MICRO OFFICE',IsActive=true,ProductCode='ABCD',SAPId__c='A0123',UnitPriceCZK__c=1000,UnitPriceEUR__c=20);
		insert prod;
		Product2 subProd = new Product2(Name='Cloth for MO',IsActive=true,ProductCode='CFMO',SAPId__c='A0456', Specification__c= '10;11');
		insert subProd;
		BOM__c bom = new BOM__c(BundleId__c=prod.Id,BundleItemId__c=subProd.Id,Quantity__c=10);
		insert bom;

		Id pricebookId = Test.getStandardPricebookId();
		String currForTest = Cst.CURR_CZK;

		// Update product price for EUR
		prod.UnitPriceEUR__c = 15;
		update prod;

		PricebookEntry pbe = [SELECT Id FROM PricebookEntry WHERE Product2Id=:prod.Id AND CurrencyIsoCode=:currForTest LIMIT 1];
		
		Opportunity opp = new Opportunity(StageName='Qualification', Name='Opp Test', CloseDate=Date.newInstance(2019, 8, 24));	
		insert opp;
		Quote qt = new Quote(Name='Quote Test', OpportunityId=opp.Id, Pricebook2Id = pricebookId);
		insert qt;
		opp.SyncedQuoteId = qt.Id;
		update opp;
		RequestForTechnician__c rft = new RequestForTechnician__c(DescriptionForTechnician__c = 'Test', QuoteId__c = qt.Id, Status__c='Done', CurrencyIsoCode=opp.CurrencyIsoCode);
		insert rft;
		Product2 prod2 = new Product2(Name='MICRO OFFICE',IsActive=true,ProductCode='ABCD',SAPId__c='A0123',UnitPriceCZK__c=1000,UnitPriceEUR__c=20, RequestForTechnicianId__c = rft.Id);
		insert prod2;
		rft.Status__c = Cst.RFT_STATUS_DONE;
		update rft;

		QuoteLineItem qli = new QuoteLineItem(QuoteId=qt.Id, Quantity=10, UnitPrice=10, Product2Id=prod.Id, PricebookEntryId = pbe.Id);
		insert qli;
		QuoteLineSubItem__c qlsi = new QuoteLineSubItem__c(QuoteLineItemId__c=qli.Id);
		insert qlsi;
		Invoice__c inv = new Invoice__c(OpportunityId__c = opp.Id, IsProforma__c = true);
		insert inv;

		Svc_OppCSVExport.exportOppsToGdrive();
		Test.stopTest();
	}
}