force-app/main/default/objects/Opportunity/fields/AccountNameText__c.field-meta.xml
<CustomField>
    <fullName>AccountNameText__c</fullName>
    <formula>Account.Name</formula>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country2__c.field-meta.xml
<CustomField>
    <fullName>Country2__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Slovakia</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IsProject__c.field-meta.xml
<CustomField>
    <fullName>IsProject__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Project</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NumericalSeries__c.field-meta.xml
<CustomField>
    <fullName>NumericalSeries__c</fullName>
    <label>Numerical Series</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityNo__c.field-meta.xml
<CustomField>
    <fullName>OpportunityNo__c</fullName>
    <label>Opportunity No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityNumber__c.field-meta.xml
<CustomField>
    <fullName>OpportunityNumber__c</fullName>
    <label>Opportunity Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ParentOpportunityId__c.field-meta.xml
<CustomField>
    <fullName>ParentOpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Child Opportunities</relationshipLabel>
    <relationshipName>ChildOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProjectNumber__c.field-meta.xml
<CustomField>
    <fullName>ProjectNumber__c</fullName>
    <description>Project Number - YY000000</description>
    <inlineHelpText>Project Number - YY000000</inlineHelpText>
    <label>Project Number</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QA_OppCreateController.cls
public class QA_OppCreateController {
	@AuraEnabled
	public static Mdl.QA_InitResponseMdl auraInit(String accId) {
		Mdl.QA_InitResponseMdl res = new Mdl.QA_InitResponseMdl();
		try {
			if(accId != null){
				res.accountCurrency = [SELECT CurrencyIsoCode FROM Account WHERE Id =: accId LIMIT 1].CurrencyIsoCode;
			}
			res.stagePickVals = Hlp.getPickVals('Opportunity', 'StageName');
			res.currencyCodes = Hlp.getPickVals('Opportunity', 'CurrencyIsoCode');
			res.countryPickVals = Hlp.getPickVals('Opportunity', 'Country2__c');
			res.countryPickVals.add(0, new Mdl.PickVal('0', '--None--'));
			res.isSuccess = true;
		} catch(Exception e) {
			res.msg = e.getMessage();
		}
		return res;
	}

	@AuraEnabled
	public static Mdl.QA_GetDuplicatesResult auraGetDuplicates(Opportunity newOpp) {
		System.debug('auraGetDuplicates() ' + newOpp);
		Mdl.QA_GetDuplicatesResult res = new Mdl.QA_GetDuplicatesResult();
		try {
			res.duplicateOpps = [SELECT Id, Name, CurrencyIsoCode, Street__c, City__c, PostalCode__c, Country__c, Country2__c, State__c, AccountId, AccountNameText__c, ParentOpportunityId__c, OpportunityNo__c, ParentOpportunityId__r.Name FROM Opportunity WHERE Street__c LIKE :newOpp.Street__c AND City__c LIKE :newOpp.City__c];
			// no posible duplicates
			if (res.duplicateOpps.size() == 0) {
				insert newOpp;
				res.isOppCreated = true;
				res.newOppId = newOpp.Id;
			}
			res.isSuccess = true;
		} catch(Exception e) {
			System.debug(e.getMessage());
			res.msg = e.getMessage();
		}
		return res;
	}

	@AuraEnabled
	public static Mdl.QA_CreateOppResult auraCreateOpp(Opportunity newOpp, Id parentOppId) {
		Savepoint sp = Database.setSavepoint();
		Mdl.QA_CreateOppResult res = new Mdl.QA_CreateOppResult();
		try {
			// No parent selected, cerate new opp directly
			if (parentOppId == null) {
				insert newOpp;
				res.newOppId = newOpp.Id;
				res.isSuccess = true;
			} else {
				// Parent opp selected, determine if parent or child is selected
				Opportunity parentOppRec = [SELECT Id, ParentOpportunityId__c FROM Opportunity WHERE Id = :parentOppId];
				// Child selected, just join under already created parent
				if (parentOppRec.ParentOpportunityId__c != null) {
					newOpp.ParentOpportunityId__c = parentOppRec.ParentOpportunityId__c;
					insert newOpp;
					res.newOppId = newOpp.Id;
					res.isSuccess = true;
				} else {
					// Standalone opp or parent selected
					Opportunity[] childOpps = [SELECT Id FROM Opportunity WHERE ParentOpportunityId__c = :parentOppRec.Id];
					// childOpps found, opp is Parent
					if (childOpps.size() > 0) {
						newOpp.ParentOpportunityId__c = parentOppRec.Id;
						insert newOpp;
						res.newOppId = newOpp.Id;
						res.isSuccess = true;
						System.debug('ChildOpp' + newOpp);
						// childOpps not found, standalone opp, create new Parent and join childs
					} else {
						// create parent
						Opportunity tmpOpp = [SELECT Id, Name, OpportunityNo__c, OpportunityNumber__c, NumericalSeries__c, ProjectNumber__c FROM Opportunity WHERE Id =: parentOppId];
						Opportunity parent = new Opportunity();
						parent.Name = Hlp.getStringWithLength('Project: ' + tmpOpp.Name, 120);
						parent.Street__c = newOpp.Street__c;
						parent.City__c = newOpp.City__c;
						parent.PostalCode__c = newOpp.PostalCode__c;
						parent.Country__c = newOpp.Country__c;
						//parent.Country2__c = newOpp.Country2__c;
						parent.State__c = newOpp.State__c;
						parent.AccountId = newOpp.AccountId;
						parent.StageName = newOpp.StageName;
						parent.CloseDate = newOpp.CloseDate;
						parent.CurrencyIsoCode = newOpp.CurrencyIsoCode;
						// Specific for project
						parent.IsProject__c = true;
						parent.OpportunityNo__c  = tmpOpp.OpportunityNo__c.substringBefore('.');
						parent.OpportunityNumber__c  = 0; // Also Project type should have Opp Number to prevent null-pointer exceptions (set to 0)
						parent.NumericalSeries__c  = tmpOpp.NumericalSeries__c;
						parent.ProjectNumber__c  = tmpOpp.ProjectNumber__c;
						System.debug('Parent' + parent);
						insert parent;
						//System.debug('After insert parent and before update child.');
						// Update child
						
						Opportunity child = new Opportunity(Id = parentOppId, ParentOpportunityId__c = parent.Id);
						update child;
						// System.debug('After update child and before insert new child.');
						// Insert new child
						newOpp.ParentOpportunityId__c = parent.Id;
						insert newOpp;
						// System.debug('After insert new child.');

						res.newOppId = newOpp.Id;
						res.isSuccess = true;
					}
				}
			}
		} catch(Exception e) {
			Database.rollback(sp);
			res.msg = e.getMessage();
		}
		return res;
	}

	@AuraEnabled
	public static String auraGetAccountCurrency(String accountId){
		return [SELECT CurrencyIsoCode FROM Account WHERE Id =: accountId LIMIT 1].CurrencyIsoCode;
	}

}