force-app/main/default/objects/Opportunity/fields/ClientReferenceNumber__c.field-meta.xml
<CustomField>
    <fullName>ClientReferenceNumber__c</fullName>
    <label>Client reference number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Dispatch_Date__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Date__c</fullName>
    <label>Dispatch Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OnSiteContactId__c.field-meta.xml
<CustomField>
    <fullName>OnSiteContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Kontaktní osoba realizace</inlineHelpText>
    <label>On-site Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (On-site Contact)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OpportunityNo__c.field-meta.xml
<CustomField>
    <fullName>OpportunityNo__c</fullName>
    <label>Opportunity No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/AccountSAPId__c.field-meta.xml
<CustomField>
    <fullName>AccountSAPId__c</fullName>
    <formula>AccountId__r.AccountEId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account SAP ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/BillingAddressTxt__c.field-meta.xml
<CustomField>
    <fullName>BillingAddressTxt__c</fullName>
    <label>Billing Address (txt)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OnSiteContactId__c.field-meta.xml
<CustomField>
    <fullName>OnSiteContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>On-site Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders (On-site Contact)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OpportunityNo__c.field-meta.xml
<CustomField>
    <fullName>OpportunityNo__c</fullName>
    <formula>OpportunityId__r.OpportunityNo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity No</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OwnerSAPId__c.field-meta.xml
<CustomField>
    <fullName>OwnerSAPId__c</fullName>
    <label>Owner SAP ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SAPOrderStatus__c.field-meta.xml
<CustomField>
    <fullName>SAPOrderStatus__c</fullName>
    <label>SAP Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SAPOrderStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/ShippingAddressTxt__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddressTxt__c</fullName>
    <label>Shipping Address (txt)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SyncStatus__c.field-meta.xml
<CustomField>
    <fullName>SyncStatus__c</fullName>
    <label>Sync Status (System)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SyncStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderLineItem__c/OrderLineItem__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderLineItem__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Line Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderLineItem__c/fields/LineNum__c.field-meta.xml
<CustomField>
    <fullName>LineNum__c</fullName>
    <label>Line Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderLineItem__c/fields/ListPrice__c.field-meta.xml
<CustomField>
    <fullName>ListPrice__c</fullName>
    <label>List Price</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderLineItem__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>OrderLineItems</relationshipLabel>
    <relationshipName>OrderLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderLineItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>OrderLineItems</relationshipLabel>
    <relationshipName>OrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderLineItem__c/fields/ProductSAPId__c.field-meta.xml
<CustomField>
    <fullName>ProductSAPId__c</fullName>
    <formula>ProductId__r.SAPId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product SAP ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderLineItem__c/fields/QuoteLineItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>OrderLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderLineItem__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <label>Subtotal</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderLineItem__c/fields/SyncStatus__c.field-meta.xml
<CustomField>
    <fullName>SyncStatus__c</fullName>
    <label>Sync Status (System)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SyncStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderLineItem__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>Total Price</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderLineItem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(ProductId__r.Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderLineItem__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Sales Price</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if Product is created in SAP and is available for adding to Quote</description>
    <inlineHelpText>Determines if Product is created in SAP and is available for adding to Quote</inlineHelpText>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SAPId__c.field-meta.xml
<CustomField>
    <fullName>SAPId__c</fullName>
    <externalId>true</externalId>
    <label>SAP ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SyncStatus__c.field-meta.xml
<CustomField>
    <fullName>SyncStatus__c</fullName>
    <label>Sync Status (System)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SyncStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>M-AKU_PENA</fullName>
            </value>
            <value>
                <fullName>M-BARVY</fullName>
            </value>
            <value>
                <fullName>M-DROBNY_SPMAT</fullName>
            </value>
            <value>
                <fullName>M-ELEKTRO</fullName>
            </value>
            <value>
                <fullName>M-FUKUMA</fullName>
            </value>
            <value>
                <fullName>M-KOV</fullName>
            </value>
            <value>
                <fullName>M-KOVANI</fullName>
            </value>
            <value>
                <fullName>M-LATKA</fullName>
            </value>
            <value>
                <fullName>M-MICROOFFICE</fullName>
            </value>
            <value>
                <fullName>M-OBALY</fullName>
            </value>
            <value>
                <fullName>M-OSTATNI</fullName>
            </value>
            <value>
                <fullName>M-PLOSNY_MAT</fullName>
            </value>
            <value>
                <fullName>M-SKLO</fullName>
            </value>
            <value>
                <fullName>P-POLOTOVAR</fullName>
            </value>
            <value>
                <fullName>S-SKLADOVE SLUZBY</fullName>
            </value>
            <value>
                <fullName>S-SLUZBY</fullName>
            </value>
            <value>
                <fullName>V-VYROBEK</fullName>
            </value>
            <value>
                <fullName>Z-ZBOZI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Quote/fields/OwnerSAPId__c.field-meta.xml
<CustomField>
    <fullName>OwnerSAPId__c</fullName>
    <formula>Owner:User.SAPId__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner SAP ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <label>Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if QLI is standard product without changes in the BOM structure</description>
    <inlineHelpText>Determines if QLI is standard product without changes in the BOM structure</inlineHelpText>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/QuoteLineSubItem__c.object-meta.xml
<CustomObject>
    <label>Quote Line Sub Item</label>
    <nameField>
        <label>Quote Line Sub Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Sub Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLineSubItem__c/fields/Product2Id__c.field-meta.xml
<CustomField>
    <fullName>Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Line Sub Items</relationshipLabel>
    <relationshipName>Quote_Line_Sub_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineSubItem__c/fields/QuoteLineItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineItemId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Quote Line Sub Items</relationshipLabel>
    <relationshipName>QuoteLineSubItems</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SyncServiceSettings__c/SyncServiceSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SyncServiceSettings</label>
</CustomObject>

force-app/main/default/objects/SyncServiceSettings__c/fields/DisableSync__c.field-meta.xml
<CustomField>
    <fullName>DisableSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/SAPOrderStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>I</fullName>
    </customValue>
    <customValue>
        <fullName>F</fullName>
    </customValue>
    <masterLabel>SAP Order Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SyncStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SUCCESS</fullName>
    </customValue>
    <customValue>
        <fullName>WARNING</fullName>
    </customValue>
    <customValue>
        <fullName>ERROR</fullName>
    </customValue>
    <customValue>
        <fullName>SYNCING</fullName>
    </customValue>
    <customValue>
        <fullName>FORCE</fullName>
    </customValue>
    <customValue>
        <fullName>HOLD</fullName>
    </customValue>
    <masterLabel>Sync Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Svc_OrderToSAP.cls
public class Svc_OrderToSAP implements Queueable, Database.AllowsCallouts {
    private static String SVC_NAME = 'OrderToSAP';

    public Set<Id> recIds{get;set;}

    public Svc_OrderToSAP(Set<Id> rIds){
        recIds = rIds;
    }

    public void execute(QueueableContext qc) {
        syncToSAP(recIds);
    }

    public static void syncToSAP(Set<Id> recIds){
        SyncServiceSettings__c stt = SyncServiceSettings__c.getValues(SVC_NAME);
        if(stt.DisableSync__c){ SyncUtils.logServiceActivity(SVC_NAME, Cst.STATUS_ERROR, 503, 'ERROR: Service is disabled'); return; }
        String dataStr;
        try{
            //SyncUtils.validateAccess(SVC_NAME);
            Order__c[] ords = [SELECT AccountId__c, AccountSAPId__c, BillingAddressTxt__c, CurrencyIsoCode, DueDate__c, OpportunityId__r.Dispatch_Date__c, Description__c, Id, Name, OpportunityNo__c, OpportunityId__r.ClientReferenceNumber__c, OwnerSAPId__c, OnSiteContactId__c, SAPOrderStatus__c, ShippingAddressTxt__c, SyncStatus__c,
                                    (SELECT Description__c, Discount__c, Id, IsDefault__c, LineNum__c, ListPrice__c, Name, OrderId__c, ProductSAPId__c, Quantity__c, QuoteLineItemId__c, Subtotal__c, TotalPrice__c, UnitPrice__c, Type__c
                                    FROM OrderLineItems__r)
                                FROM Order__c WHERE Id IN:recIds];

            Set<Id> qliIds = new Set<Id>();
            for(Order__c o : ords){
                for(OrderLineItem__c oli : o.OrderLineItems__r){
                    qliIds.add(oli.QuoteLineItemId__c);
                }
            }

            // Get primary quote Line Items (also with QLSIs)
            QuoteLineItem[] qlis = [SELECT Id,
                                        (SELECT Id, Name, Product2Id__c, Product2Id__r.SAPID__c, Product2Id__r.Description, ProductName__c, Quantity__c, QuoteLineItemId__c, Position__c
                                        FROM QuoteLineSubItems__r)
                                    FROM QuoteLineItem WHERE Id IN:qliIds];
            
            Map<Id,QuoteLineSubItem__c[]> qlsiMap = new Map<Id,QuoteLineSubItem__c[]>();

            for(QuoteLineItem qli : qlis){
                System.debug('#qli: '+qli);
                QuoteLineSubItem__c[] qlsis = (!qli.QuoteLineSubItems__r.isEmpty()) ? qli.QuoteLineSubItems__r : new QuoteLineSubItem__c[]{};
                System.debug('#qlis: '+qlis);
                qlsiMap.put(qli.Id,qlsis);
            }

            Mdl.SfOrder[] recs = new Mdl.SfOrder[]{};
            for(Order__c o : ords){
                // Map Order fields
                Mdl.SfOrder nsfo = new Mdl.SfOrder();
                nsfo.AccountId = o.AccountId__c;
                nsfo.AccountSAPId = o.AccountSAPId__c;
                nsfo.BillingAddressTxt = o.BillingAddressTxt__c;
                nsfo.CurrencyIsoCode = o.CurrencyIsoCode;
                nsfo.DueDate = o.DueDate__c;
                nsfo.DeliveryDate = o.OpportunityId__r.Dispatch_Date__c;
                nsfo.Description = o.Description__c;
                nsfo.Id = o.Id;
                nsfo.Name = o.Name;
                nsfo.OwnerSAPId = o.OwnerSAPId__c;
                nsfo.OpportunityNo = o.OpportunityNo__c;
                nsfo.PrimaryContactId = o.OnSiteContactId__c;
                nsfo.RefNo = o.OpportunityId__r.ClientReferenceNumber__c;
                nsfo.SAPOrderStatus = o.SAPOrderStatus__c;
                nsfo.ShippingAddressTxt = o.ShippingAddressTxt__c;
                nsfo.SyncStatus = o.SyncStatus__c;
                Mdl.SfOrderLineItem[] lineItems = new Mdl.SfOrderLineItem[]{};
                for(OrderLineItem__c oli : o.OrderLineItems__r){
                    // Map Order Line Item fields
                    Mdl.SfOrderLineItem noli = new Mdl.SfOrderLineItem();
                    noli.Description = oli.Description__c;
                    noli.Discount = oli.Discount__c;
                    noli.Id = oli.Id;
                    noli.IsDefault = oli.IsDefault__c;
                    noli.LineNum = (Integer)oli.LineNum__c;
                    noli.ListPrice = oli.ListPrice__c;
                    noli.Name = oli.Name;
                    noli.OrderId = oli.OrderId__c;
                    noli.ProductSAPId = oli.ProductSAPId__c;
                    noli.Quantity = oli.Quantity__c;
                    noli.Subtotal = oli.Subtotal__c;
                    noli.TotalPrice = oli.TotalPrice__c;
                    noli.UnitPrice = oli.UnitPrice__c;
                    noli.Type = oli.Type__c;
                    Mdl.SfOrderLineSubItem[] subItems = new Mdl.SfOrderLineSubItem[]{};
                    QuoteLineSubItem__c[] sis = qlsiMap.get(oli.QuoteLineItemId__c);
                    System.debug('#sis: '+sis);
                    for(QuoteLineSubItem__c si : sis){
                        // Map Order Line Sub Item fields
                        Mdl.SfOrderLineSubItem nosli = new Mdl.SfOrderLineSubItem();
                        nosli.Description = si.Product2Id__r.Description;
                        nosli.Id = si.Id;
                        nosli.Name = si.Name;
                        nosli.Product2Id = si.Product2Id__c;
                        nosli.ProductSAPId = si.Product2Id__r.SAPID__c;
                        nosli.ProductName = si.ProductName__c;
                        nosli.Quantity = si.Quantity__c;
                        nosli.QuoteLineItemId = si.QuoteLineItemId__c;
                        nosli.Position = si.Position__c;
                        subItems.add(nosli);
                    }
                    noli.OrderLineSubItems.put('Records',subItems);
                    lineItems.add(noli);
                }
                nsfo.OrderLineItems.put('Records',lineItems);
                recs.add(nsfo);
            }

            dataStr = JSON.serialize(recs, false);

            HttpResponse res = SyncUtils.sendData(SVC_NAME, dataStr);
            String status;
            if(res.getStatusCode() == 200){
                status = Cst.STATUS_SUCCESS;
                SyncUtils.logServiceActivity(SVC_NAME, Cst.STATUS_SUCCESS, res.getStatusCode(), 'SUCCESS: orders synced ('+String.join(new List<Id>(recIds),', ')+')', null, dataStr);
            }else{
                status = Cst.STATUS_ERROR;
                SyncUtils.logServiceActivity(SVC_NAME, Cst.STATUS_ERROR, res.getStatusCode(), 'ERROR - something wents wrong: ' + res.getStatus(), String.valueOf(res), dataStr);
            }
            // Set result recs
            Order__c[] recsToUpdate = new Order__c[]{};
            OrderLineItem__c[] recLinesToUpdate = new OrderLineItem__c[]{};
            for(Order__c r : ords){
                r.SyncStatus__c = status;
                recsToUpdate.add(r);
                for(OrderLineItem__c i : r.OrderLineItems__r){
                    i.SyncStatus__c = status;
                    recLinesToUpdate.add(i);
                }
            }
            update recsToUpdate;
            update recLinesToUpdate;
        }catch(Exception e){
            SyncUtils.logServiceActivity(SVC_NAME, Cst.STATUS_ERROR, 0, e.getMessage(), dataStr, e.getStackTraceString());
        }
    }
}