force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Contact_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ParentOpportunityId__c.field-meta.xml
<CustomField>
    <fullName>ParentOpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Child Opportunities</relationshipLabel>
    <relationshipName>ChildOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RealizationEndDate__c.field-meta.xml
<CustomField>
    <fullName>RealizationEndDate__c</fullName>
    <label>Realization End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RealizationStartDate__c.field-meta.xml
<CustomField>
    <fullName>RealizationStartDate__c</fullName>
    <label>Realization Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/PrimaryContactId__c.field-meta.xml
<CustomField>
    <fullName>PrimaryContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/RealizationEndDate__c.field-meta.xml
<CustomField>
    <fullName>RealizationEndDate__c</fullName>
    <label>Realization End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/RealizationStartDate__c.field-meta.xml
<CustomField>
    <fullName>RealizationStartDate__c</fullName>
    <label>Realization Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/ShippingAddressTxt__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddressTxt__c</fullName>
    <label>Shipping Address (txt)</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProjectSalesFee__c/ProjectSalesFee__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Project Sales Fee</label>
</CustomObject>

force-app/main/default/objects/ProjectSalesFee__c/fields/HigherRange__c.field-meta.xml
<CustomField>
    <fullName>HigherRange__c</fullName>
    <label>Higher Range</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ProjectSalesFee__c/fields/LowerRange__c.field-meta.xml
<CustomField>
    <fullName>LowerRange__c</fullName>
    <label>Lower Range</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ProjectSalesFee__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <label>Reward</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ProjectSalesFee__c.field-meta.xml
<CustomField>
    <fullName>ProjectSalesFee__c</fullName>
    <label>Project Sales Fee</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/ProjectSalesFeeValue__c.field-meta.xml
<CustomField>
    <fullName>ProjectSalesFeeValue__c</fullName>
    <label>Project Sales Fee Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/QuoteTotalDiscount__c.field-meta.xml
<CustomField>
    <fullName>QuoteTotalDiscount__c</fullName>
    <label>Quote Total Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SyncServiceSettings__c/SyncServiceSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SyncServiceSettings</label>
</CustomObject>

force-app/main/default/objects/SyncServiceSettings__c/fields/DisableSync__c.field-meta.xml
<CustomField>
    <fullName>DisableSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Contact_Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>Dealer</fullName>
    </customValue>
    <customValue>
        <fullName>End user</fullName>
    </customValue>
    <masterLabel>Contact Role</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HlpTest.cls
@isTest
public class HlpTest  {
    @isTest
    private static void GetStringWithLengthTest() {
        Hlp.getStringWithLength('xxx', 2);
        Hlp.getStringWithLength('', 2);

    }
    
    @isTest
    private static void GetPickValsMapTest() {
        Hlp.getPickValsMap('Opportunity', 'StageName');
    }


    @isTest
    private static void GetPickValsTest() {
        Hlp.getPickVals('Opportunity', 'StageName');
    }

    @isTest
    private static void GetPickValuesOptionsTest(){
        SyncServiceSettings__c stt = new SyncServiceSettings__c();
        stt.Name = 'AccountToSAP';
        stt.DisableSync__c = true;
        insert stt;

        Opportunity opp = new Opportunity(StageName='Qualification', Name='Opp Test', CloseDate=Date.newInstance(2019, 8, 24)); 
        insert opp;
    }

    @isTest
    private static void AfterOrderInsertTest(){
        Contact c = new Contact(LastName='Test', Email='e@e.cz', Phone='123456789', Role__c='End user');
        insert c;
        Order__c ord = new Order__c(Name='Test', RealizationStartDate__c = System.today(), RealizationEndDate__c = System.today(), ShippingAddressTxt__c = 'test', PrimaryContactId__c = c.Id);
        insert ord;
    }

    @isTest
    private static void getFormatedSubstringTest(){
        String str = 'Testovací stgring';
        String result = Hlp.getFormatedSubstring(str, 5);
    }

    @isTest
    private static void handleOppHierarchyCloseTest(){
        Account acc = new Account(Name='Test',BillingCity='Praha');
        insert acc;
        Opportunity opp = new Opportunity(StageName='Qualification', Name='Opp Test', CloseDate=Date.newInstance(2019, 8, 24), AccountId = acc.Id, Amount=10, CurrencyIsoCode='CZK');   
        insert opp;
        Opportunity opp2 = new Opportunity(StageName='Qualification', Name='Opp Test', CloseDate=Date.newInstance(2019, 8, 24), AccountId = acc.Id, ParentOpportunityId__c=opp.Id, Amount=10, CurrencyIsoCode='CZK');   
        insert opp2;
        Hlp.handleOppHierarchyClose(new Set<Id>{opp.Id}, new Set<Id>{opp2.Id});
    }

    @IsTest
    private static void should_returnValue_When_GetDatedCZKValue_ReturnZero(){
        Account acc = new Account(Name='Test', BillingCity = 'New York');
        insert acc;
        Opportunity opp = new Opportunity(StageName='Qualification', Name='Opp Test', CloseDate=Date.newInstance(2019, 8, 24), AccountId = acc.Id, Amount=10, CurrencyIsoCode='CZK');
        insert opp;
        Opportunity opp2 = new Opportunity(StageName='Qualification', Name='Opp Test', CloseDate=Date.newInstance(2019, 8, 24), AccountId = acc.Id, ParentOpportunityId__c=opp.Id, Amount=10, CurrencyIsoCode='CZK');
        insert opp2;
        Quote quote = new Quote(ProjectSalesFee__c = 12, ProjectSalesFeeValue__c = 12, QuoteTotalDiscount__c = 3, CurrencyIsoCode = 'CZK', OpportunityId = opp2.Id);
        insert quote;
        insert new ProjectSalesFee__c(Name = 'Test', LowerRange__c = 3, HigherRange__c = 4, Reward__c = 5);
        Hlp.getDatedCZKValueFromSetQT(new Set<Id>{quote.Id});

        List<Quote> quotes = [SELECT Id, ProjectSalesFeeValue__c FROM Quote];
        System.assertEquals(0, quotes.get(0).ProjectSalesFeeValue__c, 'ProjectSalesFeeValue__c should be updated to 0 based on calculations.');
    }

    @IsTest
    private static void should_returnFalse_When_areValuesDifferentGetsTwoDifferentValues() {
        Boolean result = Hlp.areValuesDifferent(null, 'Test2', false);

        Assert.areEqual(true, result, 'True should be returned as values are different');
    }

    @IsTest
    private static void should_returnTrue_When_areValuesDifferentGetsTwoSameValues() {
        Boolean result = Hlp.areValuesDifferent(123, 123, false);

        Assert.areEqual(false, result, 'False should be returned as values are the same');
    }

    @IsTest
    private static void should_returnFalse_When_areValuesDifferentGetsTwoDifferentValuesButTreatNullAsNoChangeIsSet() {
        Boolean result = Hlp.areValuesDifferent('Test1', null, true);

        Assert.areEqual(false, result, 'False should be returned as treatNullAsNoChange is set and comparedValue is null');
    }

}