force-app/main/default/objects/GoogleDriveAuth__c/GoogleDriveAuth__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Google Drive Auth</label>
</CustomObject>

force-app/main/default/objects/GoogleDriveAuth__c/fields/ProdSyncFolderEID__c.field-meta.xml
<CustomField>
    <fullName>ProdSyncFolderEID__c</fullName>
    <label>Prod Sync Folder EID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BusinessName__c.field-meta.xml
<CustomField>
    <fullName>BusinessName__c</fullName>
    <label>Business Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/BusinessNameEN__c.field-meta.xml
<CustomField>
    <fullName>BusinessNameEN__c</fullName>
    <label>Business Name EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if Product is created in SAP and is available for adding to Quote</description>
    <inlineHelpText>Determines if Product is created in SAP and is available for adding to Quote</inlineHelpText>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductDescriptionCZ__c.field-meta.xml
<CustomField>
    <fullName>ProductDescriptionCZ__c</fullName>
    <label>Product Description CZ</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductDescriptionEN__c.field-meta.xml
<CustomField>
    <fullName>ProductDescriptionEN__c</fullName>
    <label>Product Description EN</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Specification__c.field-meta.xml
<CustomField>
    <fullName>Specification__c</fullName>
    <label>Specification</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductSpecification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitCost__c.field-meta.xml
<CustomField>
    <fullName>UnitCost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceCZK__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceCZK__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price CZK</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceEUR__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceEUR__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price EUR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceUSD__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceUSD__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price USD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TemporaryRecord__c/TemporaryRecord__c.object-meta.xml
<CustomObject>
    <label>Temporary Record</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Temporary Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductUpdateControllerTest.cls
@isTest
public with sharing class ProductUpdateControllerTest {
    
    @isTest
    public static void testMethods(){
        // auraGetInitData TEST
        TemporaryRecord__c tmp = new TemporaryRecord__c(Name=Cst.RFT_TMP_RECORD_NAME);
        insert tmp;
        ProductBulkUpdateController.auraGetInitData();

        // auraGetSearchResult TEST
        ProductBulkUpdateController.auraGetSearchResult('0', '0', 'aaa');

        // auraSendExport TEST
        Product2[] prods = new Product2[]{};
        Product2 prod1 = new Product2(Name='Product', IsActive=true);
        insert prod1;
        Product2 prod2 = new Product2(Name='Product2', IsActive=true, UnitCost__c=100.00);
        insert prod2;
        prods.add(prod1);
        prods.add(prod2);
        String data = JSON.serialize(prods);
        ProductBulkUpdateController.auraSendExport(data, 'test@test.cz');

        // auraProductProcessing TEST
        ContentVersion cv = new ContentVersion(VersionData = Blob.valueOf('"Id";"Name";"Specification__c";"BusinessName__c";"BusinessNameEN__c";"Description";"ProductDescriptionCZ__c";"ProductDescriptionEN__c";"Family";"UnitCost__c";"UnitPriceCZK__c";"UnitPriceEUR__c";"UnitPriceUSD__c";"IsActive";"IsDefault__c"'+'\n'+'"01t3Y00000GTjwaQAD";"aaa";"null";"test";"null";"sd";"<p>pd cz</p>";"<p>pd en</p>";"null";"1";"2";"3";"4";"true";"true"'), Title = 'ProductExport', PathOnClient = 'PathOnClient');
        insert cv;
        ContentDocument cDoc = [SELECT Id FROM ContentDocument LIMIT 1];
        System.debug('Content Document ' + cDoc.Id);
        ProductBulkUpdateController.auraProductProcessing(cDoc.Id);

        // auraUpdateProducts TEST
        GoogleDriveAuth__c sett = new GoogleDriveAuth__c(name = 'default', ProdSyncFolderEID__c = 'xxx', TokenExpireDate__c = System.now().addMinutes(20), AccessToken__c = 'xxx');
        insert sett;
		Test.setMock(HttpCalloutMock.class, new GoogleDriveHTTPCalloutMock('{"access_token":"MTQ0NjJkZmQ5OTM2NDE1ZTZjNGZmZjI3","token_type":"bearer","expires_in":3600,"refresh_token":"IwOGYzYTlmM2YxOTQ5MGE3YmNmMDFkNTVk","scope":"create"}'));

        Test.startTest();
        ProductBulkUpdateController.auraUpdateProducts(cDoc.Id, 'test@test.cz');
        Test.stopTest();
    }

    /*=================================================================================================*/
	/* CALLOUT MOCK - CALLOUT MOCK - CALLOUT MOCK - CALLOUT MOCK - CALLOUT MOCK - CALLOUT MOCK - CALLOUT
	/*=================================================================================================*/

	public class GoogleDriveHTTPCalloutMock implements HttpCalloutMock {
		protected Integer code;
		protected String status;
		protected String body;
		protected Map<String, String> responseHeaders;
		public GoogleDriveHTTPCalloutMock(String body) { this.code = 200; this.body = body; }
		public GoogleDriveHTTPCalloutMock(Integer code, String body) { this.code = code; this.body = body; }
		public GoogleDriveHTTPCalloutMock(Integer code, String status, String body, Map<String, String> responseHeaders) {
			this.code = code; this.status = status; this.body = body; this.responseHeaders = responseHeaders;
		}
		public HTTPResponse respond(HTTPRequest req) {
			HttpResponse res = new HttpResponse();
			if (responseHeaders != null) {
				for (String key : this.responseHeaders.keySet()) { res.setHeader(key, this.responseHeaders.get(key)); }
			}
			res.setBody(this.body);
			res.setStatusCode(this.code);
			if (String.isNotEmpty(this.status)) { res.setStatus(this.status); }
			return res;
		}
	}
}