force-app/main/default/objects/ProjectSalesFee__c/ProjectSalesFee__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Project Sales Fee</label>
</CustomObject>

force-app/main/default/objects/ProjectSalesFee__c/fields/HigherRange__c.field-meta.xml
<CustomField>
    <fullName>HigherRange__c</fullName>
    <label>Higher Range</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ProjectSalesFee__c/fields/LowerRange__c.field-meta.xml
<CustomField>
    <fullName>LowerRange__c</fullName>
    <label>Lower Range</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ProjectSalesFee__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <label>Reward</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/SalesFeeManagerController.cls
public with sharing class SalesFeeManagerController {
    
    @AuraEnabled
    public static ProjectSalesFee__c[] auraGetSettings(){
        return [SELECT Name, Reward__c, LowerRange__c, HigherRange__c, Id FROM ProjectSalesFee__c ORDER BY LowerRange__c ASC];
    }

    @AuraEnabled
    public static SalesFeeMdl auraSave(ProjectSalesFee__c[] salesSettings){
        SalesFeeMdl sfm = new SalesFeeMdl();
        System.debug('AuraSave() ' + salesSettings);
        try {
            upsert salesSettings;
            sfm.isSuccess = true;
        } catch (Exception e) {
            sfm.isSuccess = false;
            sfm.message = e.getMessage();
        }
        return sfm;
    }

    public class SalesFeeMdl{
        @AuraEnabled public String 		message 		{ get; set; }
        @AuraEnabled public Boolean		isSuccess		{ get; set; }
        public SalesFeeMdl(){
        	this.isSuccess = false;
        }
    }
}